package uk.gov.mrtm.api.authorization.mrtmauth.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class MrtmPermission {
    public static final String PERM_EMP_ISSUANCE_APPLICATION_REVIEW_VIEW_TASK = "PERM_EMP_ISSUANCE_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_EMP_ISSUANCE_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_EMP_ISSUANCE_APPLICATION_REVIEW_EXECUTE_TASK";
    public static final String PERM_EMP_ISSUANCE_APPLICATION_PEER_REVIEW_VIEW_TASK = "PERM_EMP_ISSUANCE_APPLICATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_EMP_ISSUANCE_APPLICATION_PEER_REVIEW_EXECUTE_TASK = "PERM_EMP_ISSUANCE_APPLICATION_PEER_REVIEW_EXECUTE_TASK";
    public static final String PERM_EMP_VARIATION_SUBMIT_REVIEW_VIEW_TASK = "PERM_EMP_VARIATION_SUBMIT_REVIEW_VIEW_TASK";
    public static final String PERM_EMP_VARIATION_SUBMIT_REVIEW_EXECUTE_TASK = "PERM_EMP_VARIATION_SUBMIT_REVIEW_EXECUTE_TASK";
    public static final String PERM_EMP_VARIATION_PEER_REVIEW_VIEW_TASK = "PERM_EMP_VARIATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_EMP_VARIATION_PEER_REVIEW_EXECUTE_TASK = "PERM_EMP_VARIATION_PEER_REVIEW_EXECUTE_TASK";
    public static final String PERM_EMP_NOTIFICATION_REVIEW_VIEW_TASK = "PERM_EMP_NOTIFICATION_REVIEW_VIEW_TASK";
    public static final String PERM_EMP_NOTIFICATION_REVIEW_EXECUTE_TASK = "PERM_EMP_NOTIFICATION_REVIEW_EXECUTE_TASK";
    public static final String PERM_EMP_NOTIFICATION_PEER_REVIEW_VIEW_TASK = "PERM_EMP_NOTIFICATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_EMP_NOTIFICATION_PEER_REVIEW_EXECUTE_TASK = "PERM_EMP_NOTIFICATION_PEER_REVIEW_EXECUTE_TASK";
    public static final String PERM_DOE_APPLICATION_SUBMIT_VIEW_TASK = "PERM_DOE_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_DOE_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_DOE_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_DOE_PEER_REVIEW_VIEW_TASK = "PERM_DOE_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_DOE_PEER_REVIEW_EXECUTE_TASK = "PERM_DOE_PEER_REVIEW_EXECUTE_TASK";
    public static final String PERM_AER_APPLICATION_REVIEW_VIEW_TASK = "PERM_AER_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_AER_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_AER_APPLICATION_REVIEW_EXECUTE_TASK";
    public static final String PERM_VIR_APPLICATION_REVIEW_VIEW_TASK = "PERM_VIR_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_VIR_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_VIR_APPLICATION_REVIEW_EXECUTE_TASK";
    public static final String PERM_NON_COMPLIANCE_SUBMIT_VIEW_TASK = "PERM_NON_COMPLIANCE_SUBMIT_VIEW_TASK";
    public static final String PERM_NON_COMPLIANCE_SUBMIT_EXECUTE_TASK = "PERM_NON_COMPLIANCE_SUBMIT_EXECUTE_TASK";
    public static final String PERM_NON_COMPLIANCE_PEER_REVIEW_VIEW_TASK = "PERM_NON_COMPLIANCE_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_NON_COMPLIANCE_PEER_REVIEW_EXECUTE_TASK = "PERM_NON_COMPLIANCE_PEER_REVIEW_EXECUTE_TASK";
    public static final String PERM_EMP_BATCH_REISSUE_SUBMIT_VIEW_TASK = "PERM_EMP_BATCH_REISSUE_SUBMIT_VIEW_TASK";
    public static final String PERM_EMP_BATCH_REISSUE_SUBMIT_EXECUTE_TASK = "PERM_EMP_BATCH_REISSUE_SUBMIT_EXECUTE_TASK";
    public static final String PERM_ANNUAL_IMPROVEMENT_REPORT_VIEW_TASK = "PERM_ANNUAL_IMPROVEMENT_REPORT_VIEW_TASK";
    public static final String PERM_ANNUAL_IMPROVEMENT_REPORT_EXECUTE_TASK = "PERM_ANNUAL_IMPROVEMENT_REPORT_EXECUTE_TASK";
    public static final String PERM_ACCOUNT_CLOSURE_SUBMIT_VIEW_TASK = "PERM_ACCOUNT_CLOSURE_SUBMIT_VIEW_TASK";
    public static final String PERM_ACCOUNT_CLOSURE_SUBMIT_EXECUTE_TASK = "PERM_ACCOUNT_CLOSURE_SUBMIT_EXECUTE_TASK";
    public static final String PERM_EMP_ISSUANCE_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_EMP_ISSUANCE_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_EMP_ISSUANCE_APPLICATION_SUBMIT_VIEW_TASK = "PERM_EMP_ISSUANCE_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_EMP_VARIATION_APPLICATION_SUBMIT_VIEW_TASK = "PERM_EMP_VARIATION_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_EMP_VARIATION_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_EMP_VARIATION_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_VIR_APPLICATION_SUBMIT_VIEW_TASK = "PERM_VIR_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_VIR_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_VIR_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_AER_APPLICATION_SUBMIT_VIEW_TASK = "PERM_AER_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_AER_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_AER_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_DOE_MAKE_PAYMENT_VIEW_TASK = "PERM_DOE_MAKE_PAYMENT_VIEW_TASK";
    public static final String PERM_DOE_MAKE_PAYMENT_EXECUTE_TASK = "PERM_DOE_MAKE_PAYMENT_EXECUTE_TASK";
    public static final String PERM_ANNUAL_IMPROVEMENT_REPORT_SUBMIT_VIEW_TASK = "PERM_ANNUAL_IMPROVEMENT_REPORT_SUBMIT_VIEW_TASK";
    public static final String PERM_ANNUAL_IMPROVEMENT_REPORT_SUBMIT_EXECUTE_TASK = "PERM_ANNUAL_IMPROVEMENT_REPORT_SUBMIT_EXECUTE_TASK";
    public static final String PERM_EMP_NOTIFICATION_APPLICATION_SUBMIT_VIEW_TASK = "PERM_EMP_NOTIFICATION_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_EMP_NOTIFICATION_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_EMP_NOTIFICATION_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_MANAGE_GUIDANCE = "PERM_MANAGE_GUIDANCE";
    public static final String PERM_MANAGE_THIRD_PARTY_DATA_PROVIDERS = "PERM_MANAGE_THIRD_PARTY_DATA_PROVIDERS";
    public static final String PERM_SITE_VISIT_APPLICATION_REVIEW_VIEW_TASK = "PERM_SITE_VISIT_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_SITE_VISIT_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_SITE_VISIT_APPLICATION_REVIEW_EXECUTE_TASK";
    public static final String PERM_SITE_VISIT_PEER_REVIEW_VIEW_TASK = "PERM_SITE_VISIT_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_SITE_VISIT_PEER_REVIEW_EXECUTE_TASK = "PERM_SITE_VISIT_PEER_REVIEW_EXECUTE_TASK";
}
