import { MrtmRequestActionType, MrtmRequestTaskActionType, MrtmRequestType } from '@shared/types';

export const taskActionTypeToTitleMap: Record<
  MrtmRequestTaskActionType | MrtmRequestActionType | MrtmRequestType,
  string
> = {
  // MrtmRequestTaskActionType
  ACCOUNT_CLOSURE_SUBMIT: 'Close account',
  ACCOUNT_CLOSURE_SUBMITTED: 'Account closed',
  ACCOUNT_CLOSURE: 'Account closure',
  EMP_ISSUANCE: 'Emissions monitoring plan',
  EMP_ISSUANCE_APPLICATION_SUBMIT: 'Apply for an emissions monitoring plan',
  EMP_NOTIFICATION: 'Notification',
  EMP_NOTIFICATION_APPLICATION_SUBMIT: 'Notify the regulator of a change',
  EMP_NOTIFICATION_WAIT_FOR_REVIEW: 'Notification sent to regulator',
  EMP_NOTIFICATION_APPLICATION_REVIEW: 'Review notification of a change',
  EMP_NOTIFICATION_APPLICATION_PEER_REVIEW: 'Notification peer review',
  EMP_NOTIFICATION_FOLLOW_UP: 'Respond to notification follow-up',
  EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_REVIEW: 'Review notification follow-up',
  EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_REVIEW: 'Notification follow up sent to regulator',
  EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_AMENDS: 'Notification follow-up returned to operator',
  EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMIT: 'Amend your notification follow-up',
  EMP_ISSUANCE_APPLICATION_REVIEW: 'Review emissions monitoring plan application',
  EMP_VARIATION_APPLICATION_SUBMIT: 'Apply to vary the emissions monitoring plan',
  EMP_VARIATION_APPLICATION_REVIEW: 'Review emissions monitoring plan variation',
  EMP_ISSUANCE_APPLICATION_PEER_REVIEW: 'Peer review emissions monitoring plan application',
  EMP_VARIATION_WAIT_FOR_REVIEW: 'Emissions monitoring plan variation sent to regulator',
  EMP_VARIATION_WAIT_FOR_PEER_REVIEW: 'Emissions monitoring plan variation sent to peer reviewer',
  EMP_VARIATION_APPLICATION_PEER_REVIEW: 'Peer review emissions monitoring plan variation',
  EMP_ISSUANCE_WAIT_FOR_PEER_REVIEW: 'Emissions monitoring plan application sent to peer reviewer',
  EMP_ISSUANCE_WAIT_FOR_REVIEW: 'Emissions monitoring plan application sent to regulator',
  EMP_NOTIFICATION_WAIT_FOR_FOLLOW_UP: 'Notification follow-up request sent to operator',
  EMP_NOTIFICATION_WAIT_FOR_PEER_REVIEW: 'Notification sent to peer reviewer',
  EMP_ISSUANCE_APPLICATION_AMENDS_SUBMIT: 'Amend your emissions monitoring application',
  EMP_NOTIFICATION_APPLICATION_SUBMITTED: 'Notification submitted',
  EMP_NOTIFICATION_FOLLOW_UP_RESPONSE_SUBMITTED: 'Follow up response submitted',
  EMP_NOTIFICATION_APPLICATION_GRANTED: 'EMP Notification approved',
  EMP_NOTIFICATION_APPLICATION_REJECTED: 'EMP Notification rejected',
  EMP_NOTIFICATION_PEER_REVIEW_REQUESTED: 'Peer review requested',
  EMP_NOTIFICATION_APPLICATION_PEER_REVIEWER_ACCEPTED: 'Peer review approval',
  EMP_NOTIFICATION_APPLICATION_PEER_REVIEWER_REJECTED: 'Peer review rejection',
  EMP_NOTIFICATION_FOLLOW_UP_DATE_EXTENDED: 'Follow up response due date updated',
  EMP_NOTIFICATION_FOLLOW_UP_RETURNED_FOR_AMENDS: 'Follow up response returned for amends',
  EMP_NOTIFICATION_FOLLOW_UP_RECALLED_FROM_AMENDS: 'Follow up response recalled',
  EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMITTED: 'Amended follow up response submitted',
  EMP_NOTIFICATION_APPLICATION_COMPLETED: 'Notification completed',
  EMP_NOTIFICATION_APPLICATION_CANCELLED: 'Notification cancelled',
  EMP_ISSUANCE_WAIT_FOR_AMENDS: 'Emissions monitoring plan application returned to operator',
  EMP_VARIATION_REGULATOR_LED_APPLICATION_SUBMIT: 'Vary the emissions monitoring plan',
  EMP_VARIATION_UKETS_REGULATOR_LED_APPLICATION_SUBMIT: 'Vary the emissions monitoring plan',
  EMP_ISSUANCE_APPLICATION_APPROVED: 'Approved',
  EMP_ISSUANCE_APPLICATION_DEEMED_WITHDRAWN: 'Withdrawn',
  EMP_VARIATION_WAIT_FOR_AMENDS: 'Emissions monitoring plan variation returned to operator',
  EMP_VARIATION_APPLICATION_AMENDS_SUBMIT: 'Amend your emissions monitoring plan variation',
  EMP_VARIATION_REGULATOR_LED_WAIT_FOR_PEER_REVIEW: 'Emissions monitoring plan variation sent to peer reviewer',
  EMP_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEW: 'Peer review emissions monitoring plan variation',
  EMP_VARIATION_UKETS_REGULATOR_LED_APPLICATION_PEER_REVIEW: 'Peer review emissions monitoring plan variation',
  EMP_VARIATION_APPLICATION_REGULATOR_LED_APPROVED: 'Approved',
  EMP_VARIATION_APPLICATION_SUBMITTED: 'Apply to vary your emissions monitoring plan',
  EMP_VARIATION_APPLICATION_APPROVED: 'Approved',
  EMP_VARIATION_APPLICATION_REJECTED: 'Rejected',
  EMP_VARIATION_APPLICATION_DEEMED_WITHDRAWN: 'Withdrawn',
  EMP_VARIATION: 'EMP variation',
  EMP_VARIATION_APPLICATION_RETURNED_FOR_AMENDS: 'Returned to operator for amends',
  EMP_VARIATION_APPLICATION_AMENDS_SUBMITTED: 'Amends submitted',
  EMP_VARIATION_APPLICATION_PEER_REVIEWER_ACCEPTED: 'Peer review approval',
  EMP_VARIATION_APPLICATION_PEER_REVIEWER_REJECTED: 'Peer review rejection',

  // MrtmRequestActionType
  EMP_ISSUANCE_APPLICATION_SUBMITTED: 'Apply for an emissions monitoring plan',
  EMP_ISSUANCE_APPLICATION_RETURNED_FOR_AMENDS: 'Returned to operator for amends',
  EMP_ISSUANCE_APPLICATION_AMENDS_SUBMITTED: 'Apply for an emission monitoring plan amends submitted',
  EMP_ISSUANCE_APPLICATION_PEER_REVIEWER_ACCEPTED: 'Peer review approval',
  EMP_ISSUANCE_APPLICATION_PEER_REVIEWER_REJECTED: 'Peer review rejection',

  ORGANISATION_ACCOUNT_OPENING_APPLICATION_SUBMITTED: 'Original application submitted',
  ORGANISATION_ACCOUNT_OPENING_APPROVED: 'Organisation account approved',
  ORGANISATION_ACCOUNT_OPENING_REJECTED: 'Organisation account rejected',
  ORGANISATION_ACCOUNT_OPENING_CREATED: 'Original application created',

  // RDE
  EMP_ISSUANCE_WAIT_FOR_RDE_RESPONSE: 'Extension request sent to operator',
  EMP_ISSUANCE_RDE_RESPONSE_SUBMIT: 'Respond to regulator’s extension request',
  EMP_VARIATION_WAIT_FOR_RDE_RESPONSE: 'Extension request sent to operator',
  EMP_VARIATION_RDE_RESPONSE_SUBMIT: 'Respond to regulator’s extension request',
  RDE_SUBMITTED: 'Request for deadline extension',
  RDE_REJECTED: 'Response to request for deadline extension',
  RDE_FORCE_ACCEPTED: 'Deadline extension request',
  RDE_FORCE_REJECTED: 'Deadline extension request',

  // RFI
  EMP_ISSUANCE_WAIT_FOR_RFI_RESPONSE: 'Request for information sent to operator',
  EMP_ISSUANCE_RFI_RESPONSE_SUBMIT: 'Respond to regulator’s request for information',
  EMP_NOTIFICATION_WAIT_FOR_RFI_RESPONSE: 'Request for information sent to operator',
  EMP_NOTIFICATION_RFI_RESPONSE_SUBMIT: 'Respond to regulator’s request for information',
  EMP_VARIATION_WAIT_FOR_RFI_RESPONSE: 'Request for information sent to operator',
  EMP_VARIATION_RFI_RESPONSE_SUBMIT: 'Respond to regulator’s request for information',
  RFI_SUBMITTED: 'Request for information sent to operator',
  RFI_RESPONSE_SUBMITTED: 'Request for information',
  VIR_RFI_RESPONSE_SUBMIT: 'Respond to regulator’s request for information',
  VIR_WAIT_FOR_RFI_RESPONSE: 'Request for information sent to operator',

  // BATCH VARIATIONS
  EMP_REISSUE: 'Batch variation',
  EMP_REISSUE_COMPLETED: 'Batch variation completed',
  EMP_REISSUE_SUBMITTED: 'Batch variation submitted',
  EMP_BATCH_REISSUE: 'Batch variation',
  EMP_BATCH_REISSUE_SUBMITTED: 'Batch variation submitted',
  EMP_BATCH_REISSUE_COMPLETED: 'Batch variation completed',

  // AER
  AER: 'Annual emissions report',
  AER_APPLICATION_SUBMIT: 'Complete annual emissions report',
  AER_WAIT_FOR_VERIFICATION: 'Annual emissions report sent to verifier',
  AER_APPLICATION_SUBMITTED: 'Complete annual emissions report submitted to regulator',
  AER_APPLICATION_SENT_TO_VERIFIER: 'Complete annual emissions report submitted to verifier',
  AER_APPLICATION_VERIFICATION_SUBMIT: 'Verify annual emissions report',
  AER_APPLICATION_VERIFICATION_SUBMITTED: 'Verify annual emissions report submitted to operator',
  AER_RECALLED_FROM_VERIFICATION: 'Complete annual emissions report recalled from verifier',
  AER_VERIFICATION_RETURNED_TO_OPERATOR: 'Verifier returned to operator for changes',
  VERIFICATION_STATEMENT_CANCELLED: 'Verify annual emissions report cancelled due to a change of verification body',
  AER_APPLICATION_REVIEW: 'Review annual emissions report',
  AER_WAIT_FOR_AMENDS: 'Annual emissions report returned to operator',
  AER_WAIT_FOR_REVIEW: 'Annual emissions report sent to regulator for review',
  AER_APPLICATION_AMENDS_SUBMIT: 'Amend annual emissions report',
  AER_AMEND_WAIT_FOR_VERIFICATION: 'Annual emissions report sent to verifier',
  AER_AMEND_APPLICATION_VERIFICATION_SUBMIT: 'Verify annual emissions report',
  AER_APPLICATION_REVIEW_SKIPPED: 'Complete annual emissions report completed without review',
  AER_APPLICATION_COMPLETED: 'Complete annual emissions report reviewed',
  AER_APPLICATION_AMENDS_SUBMITTED: 'Complete annual emissions report amends submitted to regulator',
  AER_APPLICATION_AMENDS_SENT_TO_VERIFIER: 'Complete annual emissions report amends submitted to verifier',
  AER_APPLICATION_RETURNED_FOR_AMENDS: 'Complete annual emissions report returned for amends to operator',

  // DOE
  DOE: 'Annual determination of emissions',
  DOE_APPLICATION_SUBMIT: 'Determine annual emissions',
  DOE_WAIT_FOR_PEER_REVIEW: 'Annual emissions determination sent to peer reviewer',
  DOE_APPLICATION_PEER_REVIEW: 'Peer review annual emissions determination',
  DOE_PEER_REVIEWER_ACCEPTED: 'Peer review agreement submitted',
  DOE_PEER_REVIEWER_REJECTED: 'Peer review disagreement submitted',
  DOE_APPLICATION_SUBMITTED: 'Determine annual emissions submitted',

  // REGISTRY
  EMP_ISSUANCE_REGISTRY_ACCOUNT_OPENING_EVENT_SUBMITTED: 'Sent information to the registry',
  REGISTRY_UPDATED_EMISSIONS_EVENT_SUBMITTED: 'Emissions figure for surrender sent to Registry',
  REGISTRY_UPDATED_ACCOUNT_EVENT_SUBMITTED: 'Sent information to the registry',
  REGISTRY_REGULATOR_NOTICE_EVENT_SUBMITTED: 'Sent information to the registry',

  // VIR
  VIR: 'Annual verifier improvement report',
  VIR_APPLICATION_SUBMIT: 'Complete annual verifier improvement report',
  VIR_APPLICATION_REVIEW: 'Review annual verifier improvement report',
  VIR_RESPOND_TO_REGULATOR_COMMENTS: 'Annual verifier improvement report-responses',
  VIR_WAIT_FOR_REVIEW: 'Annual verifier improvement report sent to regulator',
  VIR_APPLICATION_SUBMITTED: 'Annual verifier improvement report submitted',
  VIR_APPLICATION_REVIEWED: 'Verifier improvement report decision submitted',
  VIR_APPLICATION_RESPONDED_TO_REGULATOR_COMMENTS: 'Follow up response',

  // PAYMENT
  EMP_ISSUANCE_MAKE_PAYMENT: 'Pay emissions monitoring plan application fee',
  EMP_ISSUANCE_CONFIRM_PAYMENT: 'Track payment for emissions monitoring plan application',
  EMP_ISSUANCE_TRACK_PAYMENT: 'Track payment for emissions monitoring plan application',

  EMP_VARIATION_TRACK_PAYMENT: 'Track payment for emissions monitoring plan variation',
  EMP_VARIATION_MAKE_PAYMENT: 'Pay emissions monitoring plan variation fee',
  EMP_VARIATION_CONFIRM_PAYMENT: 'Track payment for emissions monitoring plan variation',

  EMP_VARIATION_REGULATOR_LED_TRACK_PAYMENT: 'Track payment for emissions monitoring plan variation',
  EMP_VARIATION_REGULATOR_LED_MAKE_PAYMENT: 'Pay emissions monitoring plan variation fee',
  EMP_VARIATION_REGULATOR_LED_CONFIRM_PAYMENT: 'Track payment for emissions monitoring plan variation',

  DOE_MAKE_PAYMENT: 'Pay annual emissions determination fee',
  DOE_CONFIRM_PAYMENT: 'Track payment for annual emissions determination',
  DOE_TRACK_PAYMENT: 'Track payment for annual emissions determination',

  PAYMENT_MARKED_AS_PAID: 'Payment marked as paid',
  PAYMENT_CANCELLED: 'Payment task cancelled',
  PAYMENT_MARKED_AS_RECEIVED: 'Payment marked as received',
  PAYMENT_COMPLETED: 'Payment confirmed via GOV.UK pay',

  // SYSTEM MESSAGE NOTIFICATION
  NEW_VERIFICATION_BODY_SYSTEM_NOTIFICATION: 'New appointment from maritime operator',
  VERIFICATION_BODY_NO_LONGER_AVAILABLE_SYSTEM_NOTIFICATION: 'Verification body is no longer available',

  // NON-COMPLIANCE
  NON_COMPLIANCE: 'Non-compliance',
  NON_COMPLIANCE_APPLICATION_SUBMIT: 'Provide details of the non-compliance',
  NON_COMPLIANCE_APPLICATION_SUBMITTED: 'Non-compliance details submitted',
  NON_COMPLIANCE_INITIAL_PENALTY_NOTICE: 'Upload initial penalty notice',
  NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_WAIT_FOR_PEER_REVIEW: 'Initial penalty notice sent for peer review',
  NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_PEER_REVIEW: 'Peer review initial penalty notice',
  NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEWER_ACCEPTED: 'Peer review agreement for initial penalty submitted',
  NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEWER_REJECTED:
    'Peer review disagreement for initial penalty submitted',
  NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_SUBMITTED: 'Initial penalty notice sent to operator',
  NON_COMPLIANCE_NOTICE_OF_INTENT: 'Upload notice of intent',
  NON_COMPLIANCE_NOTICE_OF_INTENT_WAIT_FOR_PEER_REVIEW: 'Notice of intent sent for peer review',
  NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_PEER_REVIEW: 'Peer review notice of intent',
  NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEWER_ACCEPTED: 'Peer review agreement for notice of intent submitted',
  NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEWER_REJECTED: 'Peer review disagreement for notice of intent submitted',
  NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_SUBMITTED: 'Notice of intent sent to operator',
  NON_COMPLIANCE_CIVIL_PENALTY: 'Upload civil penalty notice',
  NON_COMPLIANCE_CIVIL_PENALTY_WAIT_FOR_PEER_REVIEW: 'Civil penalty notice sent for peer review',
  NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_PEER_REVIEW: 'Peer review civil penalty notice',
  NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEWER_ACCEPTED: 'Peer review agreement for civil penalty notice submitted',
  NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEWER_REJECTED: 'Peer review disagreement for civil penalty notice submitted',
  NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_SUBMITTED: 'Civil penalty notice sent to operator',
  NON_COMPLIANCE_FINAL_DETERMINATION: 'Provide non-compliance conclusion',
  NON_COMPLIANCE_FINAL_DETERMINATION_APPLICATION_SUBMITTED: 'Conclusion provided',
  NON_COMPLIANCE_APPLICATION_CLOSED: 'Non-compliance closed',
  NON_COMPLIANCE_DETAILS_AMENDED: 'Non-compliance details updated',

  //SITE VISIT
  SITE_VISIT: 'Annual virtual site visit',
  SITE_VISIT_APPLICATION_SUBMIT: 'Apply for a virtual site visit for annual',
  SITE_VISIT_WAIT_FOR_REVIEW: 'Virtual site visit application for annual sent to regulator',
  SITE_VISIT_APPLICATION_SUBMITTED: 'Virtual site visit application for annual',
  SITE_VISIT_APPLICATION_REVIEW: 'Review virtual site visit application for annual',
  SITE_VISIT_WAIT_FOR_PEER_REVIEW: 'Virtual site visit application for annual sent to peer reviewer',
  SITE_VISIT_APPLICATION_PEER_REVIEW: 'Virtual site visit application for annual peer review',
  SITE_VISIT_WAIT_FOR_AMENDS: 'Virtual site visit application for annual returned to operator',
  SITE_VISIT_APPLICATION_AMENDS_SUBMIT: 'Amend virtual site visit application for annual',
  SITE_VISIT_APPLICATION_AMENDS_SUBMITTED: 'Virtual site visit application amends for annual submitted',
  SITE_VISIT_APPLICATION_PEER_REVIEWER_ACCEPTED: 'Peer review agreement submitted',
  SITE_VISIT_APPLICATION_PEER_REVIEWER_REJECTED: 'Peer review disagreement submitted',
  SITE_VISIT_APPLICATION_RETURNED_FOR_AMENDS:
    'Virtual site visit application for annual returned to operator for amends',
  SITE_VISIT_APPLICATION_APPROVED: 'Virtual site visit application for annual accepted',
  SITE_VISIT_APPLICATION_REJECTED: 'Virtual site visit application for annual rejected',
  SITE_VISIT_APPLICATION_CANCELLED: 'Virtual site visit application for annual cancelled',
};
