<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>uk-mrtm-app-api</artifactId>
    <version>0.0.1</version>
    <packaging>jar</packaging>

    <parent>
        <groupId>uk.gov.netz</groupId>
        <artifactId>uk-netz-app-api-parent</artifactId>
        <version>1.12.0</version>
    </parent>

    <properties>
        <uk-netz-app-api-common.version>1.22.0</uk-netz-app-api-common.version>
        <uk-netz-app-api-verificationbody.version>1.5.0</uk-netz-app-api-verificationbody.version>
        <uk-netz-app-api-authorization.version>1.16.0</uk-netz-app-api-authorization.version>
        <uk-netz-app-api-account.version>1.12.0</uk-netz-app-api-account.version>
        <uk-netz-app-api-referencedata.version>1.6.0</uk-netz-app-api-referencedata.version>
        <uk-netz-app-api-token.version>1.3.0</uk-netz-app-api-token.version>
        <uk-netz-app-api-terms.version>1.2.0</uk-netz-app-api-terms.version>
        <uk-netz-app-api-competentauthority.version>1.4.0</uk-netz-app-api-competentauthority.version>
        <uk-netz-app-api-files.version>1.13.0</uk-netz-app-api-files.version>
        <uk-netz-app-api-notification.version>1.7.0</uk-netz-app-api-notification.version>
        <uk-netz-app-api-notificationapi.version>1.3.0</uk-netz-app-api-notificationapi.version>
        <uk-netz-app-api-documenttemplate.version>1.8.0</uk-netz-app-api-documenttemplate.version>
        <uk-netz-app-api-userinfoapi.version>1.2.0</uk-netz-app-api-userinfoapi.version>
        <uk-netz-app-api-mireport.version>1.13.0</uk-netz-app-api-mireport.version>
        <uk-netz-app-api-alert.version>1.2.0</uk-netz-app-api-alert.version>
        <uk-netz-app-api-rest-logging.version>1.7.0</uk-netz-app-api-rest-logging.version>
        <uk-netz-app-api-restclient.version>1.3.0</uk-netz-app-api-restclient.version>
        <uk-netz-app-api-user.version>1.10.0</uk-netz-app-api-user.version>
        <uk-netz-app-api-request.version>1.36.0</uk-netz-app-api-request.version>
        <uk-netz-app-api-swagger.version>1.2.0</uk-netz-app-api-swagger.version>
        <uk-netz-app-api-feedback.version>1.3.0</uk-netz-app-api-feedback.version>
        <uk-netz-app-api-security.version>1.6.0</uk-netz-app-api-security.version>
        <uk-netz-app-api-security-camunda-admin.version>1.1.0</uk-netz-app-api-security-camunda-admin.version>
        <uk-netz-app-api-configuration.version>1.4.0</uk-netz-app-api-configuration.version>
        <uk-netz-app-api-kafka.version>1.5.0</uk-netz-app-api-kafka.version>
        <uk-netz-app-api-doc-generator-client.version>1.0.0</uk-netz-app-api-doc-generator-client.version>
        <uk-netz-app-api-guidance.version>1.1.0</uk-netz-app-api-guidance.version>
        <uk-netz-app-api-third-party-data-provider.version>1.3.0</uk-netz-app-api-third-party-data-provider.version>
        <uk-netz-common-integration-model.version>1.10.0</uk-netz-common-integration-model.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.camunda.bpm.springboot</groupId>
            <artifactId>camunda-bpm-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flowable</groupId>
            <artifactId>flowable-spring-boot-starter-process</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-common</artifactId>
            <version>${uk-netz-app-api-common.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-verificationbody</artifactId>
            <version>${uk-netz-app-api-verificationbody.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-third-party-data-provider</artifactId>
            <version>${uk-netz-app-api-third-party-data-provider.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-authorization</artifactId>
            <version>${uk-netz-app-api-authorization.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-account</artifactId>
            <version>${uk-netz-app-api-account.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-referencedata</artifactId>
            <version>${uk-netz-app-api-referencedata.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-token</artifactId>
            <version>${uk-netz-app-api-token.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-terms</artifactId>
            <version>${uk-netz-app-api-terms.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-competentauthority</artifactId>
            <version>${uk-netz-app-api-competentauthority.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-files</artifactId>
            <version>${uk-netz-app-api-files.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-notification</artifactId>
            <version>${uk-netz-app-api-notification.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-notificationapi</artifactId>
            <version>${uk-netz-app-api-notificationapi.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-documenttemplate</artifactId>
            <version>${uk-netz-app-api-documenttemplate.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-userinfoapi</artifactId>
            <version>${uk-netz-app-api-userinfoapi.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-mireport</artifactId>
            <version>${uk-netz-app-api-mireport.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-alert</artifactId>
            <version>${uk-netz-app-api-alert.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-rest-client</artifactId>
            <version>${uk-netz-app-api-restclient.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-rest-logging</artifactId>
            <version>${uk-netz-app-api-rest-logging.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-user</artifactId>
            <version>${uk-netz-app-api-user.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-request</artifactId>
            <version>${uk-netz-app-api-request.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-swagger</artifactId>
            <version>${uk-netz-app-api-swagger.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-feedback</artifactId>
            <version>${uk-netz-app-api-feedback.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-security</artifactId>
            <version>${uk-netz-app-api-security.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-security-camunda-admin</artifactId>
            <version>${uk-netz-app-api-security-camunda-admin.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-configuration</artifactId>
            <version>${uk-netz-app-api-configuration.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-kafka</artifactId>
            <version>${uk-netz-app-api-kafka.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-doc-generator-client-aws</artifactId>
            <version>${uk-netz-app-api-doc-generator-client.version}</version>
        </dependency>

        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-common-integration-model</artifactId>
            <version>${uk-netz-common-integration-model.version}</version>
        </dependency>

        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-guidance</artifactId>
            <version>${uk-netz-app-api-guidance.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
        </dependency>

        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-cloudwatch2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.retry</groupId>
            <artifactId>spring-retry</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-csv</artifactId>
            <version>1.11.0</version>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-maven-plugin</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-apt</artifactId>
            <classifier>jakarta</classifier>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
            <classifier>jakarta</classifier>
        </dependency>
        <dependency>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.giffing.bucket4j.spring.boot.starter</groupId>
            <artifactId>bucket4j-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>jcache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.msk</groupId>
            <artifactId>aws-msk-iam-auth</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
		    <groupId>com.scalar.maven</groupId>
		    <artifactId>scalar-core</artifactId>
		    <scope>provided</scope>
		</dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>postgresql</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-compress</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.netz</groupId>
            <artifactId>uk-netz-app-api-common</artifactId>
            <classifier>tests</classifier>
            <type>test-jar</type>
            <version>${uk-netz-app-api-common.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>build-info</id>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>uk.gov.netz</groupId>
                <artifactId>swagger-coverage-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>report</id>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.hibernate.orm.tooling</groupId>
                <artifactId>hibernate-enhance-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enhance</id>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    
    <profiles>
	    <profile>
	        <id>dev-maven</id>
	        <dependencies>
	            <dependency>
	                <groupId>org.flowable</groupId>
	                <artifactId>flowable-spring-boot-starter-process-rest</artifactId>
	            </dependency>
	        </dependencies>
	    </profile>
	</profiles>
</project>
