/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AccountDetailsHistoryDTO {
  changedBy?: string;
  creationDate?: string;
  previousValue?: object;
  newValue?: object;
  reason?: string;
}
