/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountDetailsHistoryDTO } from './accountDetailsHistoryDTO';

export interface AccountDetailsHistoryListResponse {
  accountDetailsHistoryList?: Array<AccountDetailsHistoryDTO>;
}
