/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CaExternalContactDTO } from './caExternalContactDTO';

export interface CaExternalContactsDTO {
  caExternalContacts?: Array<CaExternalContactDTO>;
  editable?: boolean;
  isEditable?: boolean;
}
