/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlan } from './emissionsMonitoringPlan';
import { EmpIssuanceDetermination } from './empIssuanceDetermination';
import { EmpIssuanceReviewDecision } from './empIssuanceReviewDecision';
import { RequestTaskPreviewFileInfoDTO } from './requestTaskPreviewFileInfoDTO';

export interface EmpIssuanceApplicationAmendsSubmitRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  emissionsMonitoringPlan?: EmissionsMonitoringPlan;
  empSectionsCompleted?: { [key: string]: string };
  empAttachments?: { [key: string]: string };
  determination?: EmpIssuanceDetermination;
  accountOpeningEventSentToRegistry?: boolean;
  reviewGroupDecisions?: { [key: string]: EmpIssuanceReviewDecision };
  finalDocumentsGenerationInProgress?: boolean;
  finalDocumentsGenerationSuccessful?: boolean;
  previewFiles?: { [key: string]: RequestTaskPreviewFileInfoDTO };
  reviewAttachments?: { [key: string]: string };
  rfiAttachments?: { [key: string]: string };
  updatedSubtasks?: Array<
    | 'MARITIME_OPERATOR_DETAILS'
    | 'SHIPS_CALCULATION_EMISSIONS'
    | 'MONITORING_APPROACH'
    | 'EMISSION_SOURCES'
    | 'MANAGEMENT_PROCEDURES'
    | 'ABBREVIATIONS_AND_DEFINITIONS'
    | 'ADDITIONAL_DOCUMENTS'
    | 'DATA_GAPS'
    | 'CONTROL_ACTIVITIES'
    | 'MANDATE'
  >;
}
