/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlan } from './emissionsMonitoringPlan';
import { EmissionsMonitoringPlanContainer } from './emissionsMonitoringPlanContainer';
import { EmpAcceptedVariationDecisionDetails } from './empAcceptedVariationDecisionDetails';
import { EmpVariationDetails } from './empVariationDetails';
import { EmpVariationRegulatorLedReason } from './empVariationRegulatorLedReason';
import { RequestTaskPreviewFileInfoDTO } from './requestTaskPreviewFileInfoDTO';

export interface EmpVariationApplicationSubmitRegulatorLedRequestTaskPayload {
  payloadType?: string;
  sendEmailNotification?: boolean;
  emissionsMonitoringPlan?: EmissionsMonitoringPlan;
  empVariationDetails?: EmpVariationDetails;
  empVariationDetailsCompleted?: string;
  updatedSubtasks?: Array<
    | 'MARITIME_OPERATOR_DETAILS'
    | 'SHIPS_CALCULATION_EMISSIONS'
    | 'MONITORING_APPROACH'
    | 'EMISSION_SOURCES'
    | 'MANAGEMENT_PROCEDURES'
    | 'ABBREVIATIONS_AND_DEFINITIONS'
    | 'ADDITIONAL_DOCUMENTS'
    | 'DATA_GAPS'
    | 'CONTROL_ACTIVITIES'
    | 'MANDATE'
  >;
  empAttachments?: { [key: string]: string };
  empSectionsCompleted?: { [key: string]: string };
  originalEmpContainer?: EmissionsMonitoringPlanContainer;
  reasonRegulatorLed: EmpVariationRegulatorLedReason;
  reviewGroupDecisions?: { [key: string]: EmpAcceptedVariationDecisionDetails };
  finalDocumentsGenerationInProgress?: boolean;
  finalDocumentsGenerationSuccessful?: boolean;
  previewFiles?: { [key: string]: RequestTaskPreviewFileInfoDTO };
}
