/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MrtmAccountSearchCriteria {
  /**
   * Search by emitter ID, account name, IMO number or Registry ID
   */
  term?: string;
  /**
   * Account statuses filter
   */
  statuses?: Array<'NEW' | 'LIVE' | 'CLOSED' | 'WITHDRAWN'>;
  /**
   * Contact email used for user-assignment filtering
   */
  contactEmail?: string;
  /**
   * Supported values: OPERATOR_NAME, ACCOUNT_ID, STATUS, IMO_NUMBER
   */
  sortBy?: string;
  /**
   * Sort direction. Supported values: ASC, DESC
   */
  direction?: 'ASC' | 'DESC';
  /**
   * Zero-based page index. Defaults to 0 when omitted.
   */
  page?: number;
  /**
   * Page size. Defaults to 20 when omitted.
   */
  size?: number;
}
