/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileInfoDTO } from './fileInfoDTO';

export interface RequestTaskPreviewFileInfoDTO {
  asyncJobId?: string;
  status?: 'IN_PROGRESS' | 'COMPLETED' | 'FAILED';
  file?: FileInfoDTO;
  createdDate?: string;
}
