/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';
import { SiteVisit } from './siteVisit';
import { SiteVisitReviewDecision } from './siteVisitReviewDecision';

export interface SiteVisitApplicationReviewSubmittedRequestActionPayload {
  payloadType?: string;
  siteVisit: SiteVisit;
  sectionsCompleted?: { [key: string]: string };
  siteVisitAttachments?: { [key: string]: string };
  reviewDecision: SiteVisitReviewDecision;
  decisionNotification: DecisionNotification;
  reviewAttachments?: { [key: string]: string };
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialNotice: FileInfoDTO;
}
