/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SiteVisitReviewDecision } from './siteVisitReviewDecision';

export interface SiteVisitApplicationReturnedForAmendsRequestActionPayload {
  payloadType?: string;
  reviewDecision?: SiteVisitReviewDecision;
  sectionsCompleted?: { [key: string]: string };
  reviewAttachments?: { [key: string]: string };
}
