/**
 * API Documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SiteVisit } from './siteVisit';

export interface SiteVisitSaveApplicationAmendRequestTaskActionPayload {
  payloadType?: string;
  siteVisit: SiteVisit;
  sectionsCompleted?: { [key: string]: string };
  updatedSubtask?: boolean;
}
