spring.application.name=uk-mrtm-app-data-provider-emulator
# Configure the HTTP port for the Spring Boot application
server.servlet.context-path=/data-emulator
server.port=9109

# Expose actuator health at /data-emulator/health for DevOps probes/metrics
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=health

keycloak.base-url=${KEYCLOAK_BASE_URL:http://keycloak:8080}
keycloak.token-url=${keycloak.base-url}/auth/realms/uk-pmrv/protocol/openid-connect/token
keycloak.audience=${KEYCLOAK_AUDIENCE_URL:http://localhost:8080/auth/realms/uk-pmrv}

emulator.jwkSet.json=${JWK_SET:}
app.security.username=${API_USERNAME}
app.security.password=${API_PASSWORD}
emulator.jwkSet.count=${JWK_SET_COUNT:10}