import { CancelActionsMap } from '@netz/common/cancel-task';

export const cancelActionsMap: CancelActionsMap = {
  ACCOUNT_CLOSURE_SUBMIT: {
    actionType: 'ACCOUNT_CLOSURE_CANCEL_APPLICATION',
  },
  EMP_NOTIFICATION_APPLICATION_SUBMIT: {
    actionType: 'EMP_NOTIFICATION_CANCEL_APPLICATION',
  },
  EMP_VARIATION_APPLICATION_SUBMIT: {
    actionType: 'EMP_VARIATION_CANCEL_APPLICATION',
  },
  EMP_VARIATION_REGULATOR_LED_APPLICATION_SUBMIT: {
    actionType: 'EMP_VARIATION_CANCEL_APPLICATION',
  },
  EMP_ISSUANCE_WAIT_FOR_RFI_RESPONSE: {
    actionType: 'CANCEL_APPLICATION',
  },
  EMP_VARIATION_WAIT_FOR_RFI_RESPONSE: {
    actionType: 'CANCEL_APPLICATION',
  },
  EMP_NOTIFICATION_WAIT_FOR_RFI_RESPONSE: {
    actionType: 'CANCEL_APPLICATION',
  },
  DOE_APPLICATION_SUBMIT: {
    actionType: 'DOE_CANCEL_APPLICATION',
  },
  VIR_WAIT_FOR_RFI_RESPONSE: {
    actionType: 'CANCEL_APPLICATION',
  },
  SITE_VISIT_APPLICATION_SUBMIT: {
    actionType: 'SITE_VISIT_CANCEL_APPLICATION',
  },
};
