import { RequestTaskDTO } from '@mrtm/api';

export type MrtmRequestTaskType =
  | RequestTaskDTO['type']

  /**
   * ACCOUNT_CLOSURE
   */
  | 'ACCOUNT_CLOSURE_SUBMIT'

  /**
   * EMP_ISSUANCE
   */
  | 'EMP_ISSUANCE_APPLICATION_SUBMIT'
  | 'EMP_ISSUANCE_APPLICATION_REVIEW'
  | 'EMP_ISSUANCE_WAIT_FOR_REVIEW'
  | 'EMP_ISSUANCE_APPLICATION_PEER_REVIEW'
  | 'EMP_ISSUANCE_WAIT_FOR_PEER_REVIEW'
  | 'EMP_ISSUANCE_APPLICATION_AMENDS_SUBMIT'
  | 'EMP_ISSUANCE_WAIT_FOR_AMENDS'
  | 'EMP_ISSUANCE_RDE_RESPONSE_SUBMIT'
  | 'EMP_ISSUANCE_WAIT_FOR_RDE_RESPONSE'
  | 'EMP_ISSUANCE_RFI_RESPONSE_SUBMIT'
  | 'EMP_ISSUANCE_WAIT_FOR_RFI_RESPONSE'
  | 'EMP_ISSUANCE_MAKE_PAYMENT'
  | 'EMP_ISSUANCE_TRACK_PAYMENT'
  | 'EMP_ISSUANCE_CONFIRM_PAYMENT'

  /**
   * EMP_NOTIFICATION
   */
  | 'EMP_NOTIFICATION_APPLICATION_SUBMIT'
  | 'EMP_NOTIFICATION_APPLICATION_REVIEW'
  | 'EMP_NOTIFICATION_WAIT_FOR_REVIEW'
  | 'EMP_NOTIFICATION_APPLICATION_PEER_REVIEW'
  | 'EMP_NOTIFICATION_WAIT_FOR_PEER_REVIEW'
  | 'EMP_NOTIFICATION_FOLLOW_UP'
  | 'EMP_NOTIFICATION_WAIT_FOR_FOLLOW_UP'
  | 'EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_REVIEW'
  | 'EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_REVIEW'
  | 'EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMIT'
  | 'EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_AMENDS'

  /**
   * EMP_VARIATION
   */
  | 'EMP_VARIATION_APPLICATION_SUBMIT'
  | 'EMP_VARIATION_APPLICATION_REVIEW'
  | 'EMP_VARIATION_WAIT_FOR_REVIEW'
  | 'EMP_VARIATION_APPLICATION_PEER_REVIEW'
  | 'EMP_VARIATION_WAIT_FOR_PEER_REVIEW'
  | 'EMP_VARIATION_REGULATOR_LED_APPLICATION_SUBMIT'
  | 'EMP_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEW'
  | 'EMP_VARIATION_REGULATOR_LED_WAIT_FOR_PEER_REVIEW'
  | 'EMP_VARIATION_APPLICATION_AMENDS_SUBMIT'
  | 'EMP_VARIATION_WAIT_FOR_AMENDS'
  | 'EMP_VARIATION_RDE_RESPONSE_SUBMIT'
  | 'EMP_VARIATION_WAIT_FOR_RDE_RESPONSE'
  | 'EMP_VARIATION_RFI_RESPONSE_SUBMIT'
  | 'EMP_VARIATION_WAIT_FOR_RFI_RESPONSE'
  | 'EMP_VARIATION_MAKE_PAYMENT'
  | 'EMP_VARIATION_TRACK_PAYMENT'
  | 'EMP_VARIATION_CONFIRM_PAYMENT'
  | 'EMP_VARIATION_REGULATOR_LED_MAKE_PAYMENT'
  | 'EMP_VARIATION_REGULATOR_LED_TRACK_PAYMENT'
  | 'EMP_VARIATION_REGULATOR_LED_CONFIRM_PAYMENT'

  /**
   * AER
   */
  | 'AER_APPLICATION_SUBMIT'
  | 'AER_APPLICATION_VERIFICATION_SUBMIT'
  | 'AER_WAIT_FOR_VERIFICATION'
  | 'AER_APPLICATION_REVIEW'
  | 'AER_WAIT_FOR_REVIEW'
  | 'AER_APPLICATION_AMENDS_SUBMIT'
  | 'AER_WAIT_FOR_AMENDS'
  | 'AER_AMEND_APPLICATION_VERIFICATION_SUBMIT'
  | 'AER_AMEND_WAIT_FOR_VERIFICATION'

  /**
   * DOE
   */
  | 'DOE_APPLICATION_SUBMIT'
  | 'DOE_APPLICATION_PEER_REVIEW'
  | 'DOE_WAIT_FOR_PEER_REVIEW'
  | 'DOE_MAKE_PAYMENT'
  | 'DOE_TRACK_PAYMENT'
  | 'DOE_CONFIRM_PAYMENT'

  /**
   * VIR
   */
  | 'VIR_APPLICATION_SUBMIT'
  | 'VIR_APPLICATION_REVIEW'
  | 'VIR_WAIT_FOR_REVIEW'
  | 'VIR_RESPOND_TO_REGULATOR_COMMENTS'
  | 'VIR_RFI_RESPONSE_SUBMIT'
  | 'VIR_WAIT_FOR_RFI_RESPONSE'

  /**
   * NON_COMPLIANCE
   */
  | 'NON_COMPLIANCE_APPLICATION_SUBMIT'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_PEER_REVIEW'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_WAIT_FOR_PEER_REVIEW'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_PEER_REVIEW'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_WAIT_FOR_PEER_REVIEW'
  | 'NON_COMPLIANCE_CIVIL_PENALTY'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_PEER_REVIEW'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_WAIT_FOR_PEER_REVIEW'
  | 'NON_COMPLIANCE_FINAL_DETERMINATION'

  /**
   * SITE_VISIT
   */
  | 'SITE_VISIT_APPLICATION_SUBMIT';
