import { RequestActionDTO } from '@mrtm/api';

export type MrtmRequestActionType =
  | RequestActionDTO['type']
  | 'REQUEST_TERMINATED'

  /**
   * ACCOUNT_CLOSURE
   */
  | 'ACCOUNT_CLOSURE_SUBMITTED'
  | 'ACCOUNT_CLOSURE_CANCELLED'

  /**
   * EMP_ISSUANCE
   */
  | 'EMP_ISSUANCE_APPLICATION_SUBMITTED'
  | 'EMP_ISSUANCE_APPLICATION_APPROVED'
  | 'EMP_ISSUANCE_APPLICATION_DEEMED_WITHDRAWN'
  | 'EMP_ISSUANCE_PEER_REVIEW_REQUESTED'
  | 'EMP_ISSUANCE_REGISTRY_ACCOUNT_OPENING_EVENT_SUBMITTED'
  | 'EMP_ISSUANCE_APPLICATION_PEER_REVIEWER_ACCEPTED'
  | 'EMP_ISSUANCE_APPLICATION_PEER_REVIEWER_REJECTED'
  | 'EMP_ISSUANCE_APPLICATION_RETURNED_FOR_AMENDS'
  | 'EMP_ISSUANCE_APPLICATION_AMENDS_SUBMITTED'
  | 'EMP_ISSUANCE_RECALLED_FROM_AMENDS'

  /**
   * EMP_NOTIFICATION
   */
  | 'EMP_NOTIFICATION_APPLICATION_SUBMITTED'
  | 'EMP_NOTIFICATION_APPLICATION_CANCELLED'
  | 'EMP_NOTIFICATION_APPLICATION_GRANTED'
  | 'EMP_NOTIFICATION_APPLICATION_REJECTED'
  | 'EMP_NOTIFICATION_APPLICATION_COMPLETED'
  | 'EMP_NOTIFICATION_PEER_REVIEW_REQUESTED'
  | 'EMP_NOTIFICATION_APPLICATION_PEER_REVIEWER_ACCEPTED'
  | 'EMP_NOTIFICATION_APPLICATION_PEER_REVIEWER_REJECTED'
  | 'EMP_NOTIFICATION_FOLLOW_UP_RESPONSE_SUBMITTED'
  | 'EMP_NOTIFICATION_FOLLOW_UP_DATE_EXTENDED'
  | 'EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMITTED'
  | 'EMP_NOTIFICATION_FOLLOW_UP_RETURNED_FOR_AMENDS'
  | 'EMP_NOTIFICATION_FOLLOW_UP_RECALLED_FROM_AMENDS'

  /**
   * EMP VARIATION
   */
  | 'EMP_VARIATION_APPLICATION_SUBMITTED'
  | 'EMP_VARIATION_APPLICATION_APPROVED'
  | 'EMP_VARIATION_APPLICATION_REJECTED'
  | 'EMP_VARIATION_APPLICATION_DEEMED_WITHDRAWN'
  | 'EMP_VARIATION_PEER_REVIEW_REQUESTED'
  | 'EMP_VARIATION_APPLICATION_REGULATOR_LED_APPROVED'
  | 'EMP_VARIATION_APPLICATION_PEER_REVIEWER_ACCEPTED'
  | 'EMP_VARIATION_APPLICATION_PEER_REVIEWER_REJECTED'
  | 'EMP_VARIATION_APPLICATION_CANCELLED'
  | 'EMP_VARIATION_APPLICATION_RETURNED_FOR_AMENDS'
  | 'EMP_VARIATION_APPLICATION_AMENDS_SUBMITTED'
  | 'EMP_VARIATION_RECALLED_FROM_AMENDS'

  /**
   * BATCH REISSUE
   */
  | 'EMP_BATCH_REISSUE_SUBMITTED'
  | 'EMP_BATCH_REISSUE_COMPLETED'
  | 'EMP_REISSUE_COMPLETED'

  /**
   * AER
   */
  | 'AER_APPLICATION_CANCELLED_DUE_TO_EXEMPT'
  | 'AER_APPLICATION_EXEMPTION_REVERTED'
  | 'AER_APPLICATION_RE_INITIATED'
  | 'AER_APPLICATION_SENT_TO_VERIFIER'
  | 'AER_APPLICATION_SUBMITTED'
  | 'AER_APPLICATION_VERIFICATION_SUBMITTED'
  | 'AER_VERIFICATION_RETURNED_TO_OPERATOR'
  | 'AER_RECALLED_FROM_VERIFICATION'
  | 'AER_APPLICATION_REVIEW_SKIPPED'
  | 'AER_APPLICATION_COMPLETED'
  | 'AER_APPLICATION_RETURNED_FOR_AMENDS'
  | 'AER_APPLICATION_AMENDS_SENT_TO_VERIFIER'
  | 'AER_APPLICATION_AMENDS_SUBMITTED'

  /**
   * DOE
   */
  | 'DOE_APPLICATION_SUBMITTED'
  | 'DOE_APPLICATION_CANCELLED'
  | 'DOE_PEER_REVIEW_REQUESTED'
  | 'DOE_PEER_REVIEWER_ACCEPTED'
  | 'DOE_PEER_REVIEWER_REJECTED'
  | 'DOE_APPLICATION_CANCELLED_DUE_TO_EXEMPT'

  /**
   * VIR
   */
  | 'VIR_APPLICATION_SUBMITTED'
  | 'VIR_APPLICATION_REVIEWED'
  | 'VIR_APPLICATION_RESPONDED_TO_REGULATOR_COMMENTS'

  /**
   * REGISTRY
   */
  | 'REGISTRY_UPDATED_EMISSIONS_EVENT_SUBMITTED'
  | 'REGISTRY_UPDATED_ACCOUNT_EVENT_SUBMITTED'
  | 'REGISTRY_REGULATOR_NOTICE_EVENT_SUBMITTED'

  /**
   * NON_COMPLIANCE
   */
  | 'NON_COMPLIANCE_APPLICATION_SUBMITTED'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEW_REQUESTED'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEWER_ACCEPTED'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEWER_REJECTED'
  | 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_SUBMITTED'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEW_REQUESTED'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEWER_ACCEPTED'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEWER_REJECTED'
  | 'NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_SUBMITTED'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_SUBMITTED'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEW_REQUESTED'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEWER_ACCEPTED'
  | 'NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEWER_REJECTED'
  | 'NON_COMPLIANCE_FINAL_DETERMINATION_APPLICATION_SUBMITTED'
  | 'NON_COMPLIANCE_APPLICATION_CLOSED'
  | 'NON_COMPLIANCE_DETAILS_AMENDED'

  /**
   * SITE_VISIT
   */
  | 'SITE_VISIT_APPLICATION_SUBMIT'
  | 'SITE_VISIT_WAIT_FOR_REVIEW';
