import { MrtmRequestTaskActionPayloadType, MrtmRequestTaskActionType, MrtmRequestTaskPayloadType } from '@shared/types';

export const notifyOperatorActionPayloadMap: Record<
  MrtmRequestTaskPayloadType,
  {
    requestTaskActionType: MrtmRequestTaskActionType;
    payloadType: MrtmRequestTaskActionPayloadType;
  }
> = {
  EMP_NOTIFICATION_APPLICATION_REVIEW_PAYLOAD: {
    requestTaskActionType: 'EMP_NOTIFICATION_NOTIFY_OPERATOR_FOR_DECISION',
    payloadType: 'EMP_NOTIFICATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD',
  },
  EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_REVIEW_PAYLOAD: {
    requestTaskActionType: 'EMP_NOTIFICATION_FOLLOW_UP_NOTIFY_OPERATOR_FOR_DECISION',
    payloadType: 'EMP_NOTIFICATION_FOLLOW_UP_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD',
  },
  EMP_ISSUANCE_APPLICATION_REVIEW_PAYLOAD: {
    requestTaskActionType: 'EMP_ISSUANCE_NOTIFY_OPERATOR_FOR_DECISION',
    payloadType: 'EMP_ISSUANCE_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD',
  },
  EMP_VARIATION_APPLICATION_SUBMIT_REGULATOR_LED_PAYLOAD: {
    requestTaskActionType: 'EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_REGULATOR_LED',
    payloadType: 'EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_REGULATOR_LED_PAYLOAD',
  },
  EMP_VARIATION_APPLICATION_REVIEW_PAYLOAD: {
    requestTaskActionType: 'EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION',
    payloadType: 'EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD',
  },
  DOE_APPLICATION_SUBMIT_PAYLOAD: {
    requestTaskActionType: 'DOE_SUBMIT_NOTIFY_OPERATOR',
    payloadType: 'DOE_SUBMIT_NOTIFY_OPERATOR_PAYLOAD',
  },
  VIR_APPLICATION_REVIEW_PAYLOAD: {
    requestTaskActionType: 'VIR_NOTIFY_OPERATOR_FOR_DECISION',
    payloadType: 'VIR_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD',
  },
  NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PAYLOAD: {
    requestTaskActionType: 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_NOTIFY_OPERATOR',
    payloadType: 'NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_NOTIFY_OPERATOR_PAYLOAD',
  },
  NON_COMPLIANCE_NOTICE_OF_INTENT_PAYLOAD: {
    requestTaskActionType: 'NON_COMPLIANCE_NOTICE_OF_INTENT_NOTIFY_OPERATOR',
    payloadType: 'NON_COMPLIANCE_NOTICE_OF_INTENT_NOTIFY_OPERATOR_PAYLOAD',
  },
  NON_COMPLIANCE_CIVIL_PENALTY_PAYLOAD: {
    requestTaskActionType: 'NON_COMPLIANCE_CIVIL_PENALTY_NOTIFY_OPERATOR',
    payloadType: 'NON_COMPLIANCE_CIVIL_PENALTY_NOTIFY_OPERATOR_PAYLOAD',
  },
  SITE_VISIT_APPLICATION_REVIEW_PAYLOAD: {
    requestTaskActionType: 'SITE_VISIT_NOTIFY_OPERATOR_FOR_DECISION',
    payloadType: 'SITE_VISIT_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD',
  },
};
