package uk.gov.mrtm.api.workflow.request.core.domain.constants;

import lombok.experimental.UtilityClass;

@UtilityClass
public class MrtmRequestTaskPayloadType {
    /**
     * ACCOUNT_CLOSURE
     */
    public static final String ACCOUNT_CLOSURE_SUBMIT_PAYLOAD = "ACCOUNT_CLOSURE_SUBMIT_PAYLOAD";

    /**
     * EMP_ISSUANCE
     */
    public static final String EMP_ISSUANCE_APPLICATION_SUBMIT_PAYLOAD = "EMP_ISSUANCE_APPLICATION_SUBMIT_PAYLOAD";
    public static final String EMP_ISSUANCE_WAIT_FOR_REVIEW_PAYLOAD = "EMP_ISSUANCE_WAIT_FOR_REVIEW_PAYLOAD";
    public static final String EMP_ISSUANCE_APPLICATION_REVIEW_PAYLOAD = "EMP_ISSUANCE_APPLICATION_REVIEW_PAYLOAD";
    public static final String EMP_ISSUANCE_APPLICATION_PEER_REVIEW_PAYLOAD = "EMP_ISSUANCE_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String EMP_ISSUANCE_WAIT_FOR_PEER_REVIEW_PAYLOAD = "EMP_ISSUANCE_WAIT_FOR_PEER_REVIEW_PAYLOAD";
    public static final String EMP_ISSUANCE_APPLICATION_AMENDS_SUBMIT_PAYLOAD = "EMP_ISSUANCE_APPLICATION_AMENDS_SUBMIT_PAYLOAD";
    public static final String EMP_ISSUANCE_WAIT_FOR_AMENDS_PAYLOAD = "EMP_ISSUANCE_WAIT_FOR_AMENDS_PAYLOAD";

    /**
     * EMP_NOTIFICATION
     */
    public static final String EMP_NOTIFICATION_APPLICATION_SUBMIT_PAYLOAD = "EMP_NOTIFICATION_APPLICATION_SUBMIT_PAYLOAD";
    public static final String EMP_NOTIFICATION_APPLICATION_REVIEW_PAYLOAD = "EMP_NOTIFICATION_APPLICATION_REVIEW_PAYLOAD";
    public static final String EMP_NOTIFICATION_APPLICATION_PEER_REVIEW_PAYLOAD = "EMP_NOTIFICATION_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String EMP_NOTIFICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD = "EMP_NOTIFICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD";
    public static final String EMP_NOTIFICATION_WAIT_FOR_FOLLOW_UP_PAYLOAD = "EMP_NOTIFICATION_WAIT_FOR_FOLLOW_UP_PAYLOAD";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_PAYLOAD = "EMP_NOTIFICATION_FOLLOW_UP_PAYLOAD";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_REVIEW_PAYLOAD = "EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_REVIEW_PAYLOAD";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMIT_PAYLOAD = "EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMIT_PAYLOAD";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_AMENDS_PAYLOAD = "EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_AMENDS_PAYLOAD";

    /**
     * EMP_VARIATION
     */
    public static final String EMP_VARIATION_APPLICATION_SUBMIT_PAYLOAD = "EMP_VARIATION_APPLICATION_SUBMIT_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_REVIEW_PAYLOAD = "EMP_VARIATION_APPLICATION_REVIEW_PAYLOAD";
    public static final String EMP_VARIATION_WAIT_FOR_REVIEW_PAYLOAD = "EMP_VARIATION_WAIT_FOR_REVIEW_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_SUBMIT_REGULATOR_LED_PAYLOAD = "EMP_VARIATION_APPLICATION_SUBMIT_REGULATOR_LED_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_PEER_REVIEW_PAYLOAD = "EMP_VARIATION_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD = "EMP_VARIATION_APPLICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_PEER_REVIEW_REGULATOR_LED_PAYLOAD = "EMP_VARIATION_APPLICATION_PEER_REVIEW_REGULATOR_LED_PAYLOAD";
    public static final String EMP_VARIATION_WAIT_FOR_PEER_REVIEW_REGULATOR_LED_PAYLOAD = "EMP_VARIATION_WAIT_FOR_PEER_REVIEW_REGULATOR_LED_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_AMENDS_SUBMIT_PAYLOAD = "EMP_VARIATION_APPLICATION_AMENDS_SUBMIT_PAYLOAD";
    public static final String EMP_VARIATION_WAIT_FOR_AMENDS_PAYLOAD = "EMP_VARIATION_WAIT_FOR_AMENDS_PAYLOAD";

    /**
     * AER
     */
    public static final String AER_APPLICATION_SUBMIT_PAYLOAD = "AER_APPLICATION_SUBMIT_PAYLOAD";
    public static final String AER_APPLICATION_VERIFICATION_SUBMIT_PAYLOAD = "AER_APPLICATION_VERIFICATION_SUBMIT_PAYLOAD";
    public static final String AER_APPLICATION_REVIEW_PAYLOAD = "AER_APPLICATION_REVIEW_PAYLOAD";
    public static final String AER_APPLICATION_AMENDS_SUBMIT_PAYLOAD = "AER_APPLICATION_AMENDS_SUBMIT_PAYLOAD";
    public static final String AER_WAIT_FOR_AMENDS_PAYLOAD = "AER_WAIT_FOR_AMENDS_PAYLOAD";

    /**
     * DOE
     */
    public static final String DOE_APPLICATION_SUBMIT_PAYLOAD = "DOE_APPLICATION_SUBMIT_PAYLOAD";
    public static final String DOE_APPLICATION_PEER_REVIEW_PAYLOAD = "DOE_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String DOE_WAIT_FOR_PEER_REVIEW_PAYLOAD = "DOE_WAIT_FOR_PEER_REVIEW_PAYLOAD";

    /**
     * VIR
     */
    public static final String VIR_APPLICATION_SUBMIT_PAYLOAD = "VIR_APPLICATION_SUBMIT_PAYLOAD";
    public static final String VIR_APPLICATION_REVIEW_PAYLOAD = "VIR_APPLICATION_REVIEW_PAYLOAD";
    public static final String VIR_RESPOND_TO_REGULATOR_COMMENTS_PAYLOAD = "VIR_RESPOND_TO_REGULATOR_COMMENTS_PAYLOAD";

    /**
     * NON_COMPLIANCE
     */
    public static final String NON_COMPLIANCE_APPLICATION_SUBMIT_PAYLOAD = "NON_COMPLIANCE_APPLICATION_SUBMIT_PAYLOAD";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PAYLOAD = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PAYLOAD";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_PEER_REVIEW_PAYLOAD = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_WAIT_FOR_PEER_REVIEW_PAYLOAD = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_WAIT_FOR_PEER_REVIEW_PAYLOAD";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_PAYLOAD = "NON_COMPLIANCE_NOTICE_OF_INTENT_PAYLOAD";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_PEER_REVIEW_PAYLOAD = "NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_WAIT_FOR_PEER_REVIEW_PAYLOAD = "NON_COMPLIANCE_NOTICE_OF_INTENT_WAIT_FOR_PEER_REVIEW_PAYLOAD";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_PAYLOAD = "NON_COMPLIANCE_CIVIL_PENALTY_PAYLOAD";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_PEER_REVIEW_PAYLOAD = "NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_WAIT_FOR_PEER_REVIEW_PAYLOAD = "NON_COMPLIANCE_CIVIL_PENALTY_WAIT_FOR_PEER_REVIEW_PAYLOAD";
    public static final String NON_COMPLIANCE_FINAL_DETERMINATION_PAYLOAD = "NON_COMPLIANCE_FINAL_DETERMINATION_PAYLOAD";

    /**
     * SITE_VISIT
     */
    public static final String SITE_VISIT_APPLICATION_SUBMIT_PAYLOAD = "SITE_VISIT_APPLICATION_SUBMIT_PAYLOAD";
    public static final String SITE_VISIT_APPLICATION_REVIEW_PAYLOAD = "SITE_VISIT_APPLICATION_REVIEW_PAYLOAD";
    public static final String SITE_VISIT_WAIT_FOR_REVIEW_PAYLOAD = "SITE_VISIT_WAIT_FOR_REVIEW_PAYLOAD";
    public static final String SITE_VISIT_APPLICATION_PEER_REVIEW_PAYLOAD = "SITE_VISIT_APPLICATION_PEER_REVIEW_PAYLOAD";
    public static final String SITE_VISIT_WAIT_FOR_PEER_REVIEW_PAYLOAD = "SITE_VISIT_WAIT_FOR_PEER_REVIEW_PAYLOAD";
    public static final String SITE_VISIT_APPLICATION_AMENDS_SUBMIT_PAYLOAD = "SITE_VISIT_APPLICATION_AMENDS_SUBMIT_PAYLOAD";
    public static final String SITE_VISIT_WAIT_FOR_AMENDS_PAYLOAD = "SITE_VISIT_WAIT_FOR_AMENDS_PAYLOAD";
}
