package uk.gov.mrtm.api.workflow.request.core.domain.constants;

import lombok.experimental.UtilityClass;

@UtilityClass
public class MrtmRequestActionType {
    public static final String REQUEST_TERMINATED = "REQUEST_TERMINATED";

    /**
     * ACCOUNT_CLOSURE
     */
    public static final String ACCOUNT_CLOSURE_SUBMITTED = "ACCOUNT_CLOSURE_SUBMITTED";
    public static final String ACCOUNT_CLOSURE_CANCELLED = "ACCOUNT_CLOSURE_CANCELLED";

    /**
     * EMP_ISSUANCE
     */
    public static final String EMP_ISSUANCE_APPLICATION_SUBMITTED = "EMP_ISSUANCE_APPLICATION_SUBMITTED";
    public static final String EMP_ISSUANCE_APPLICATION_APPROVED = "EMP_ISSUANCE_APPLICATION_APPROVED";
    public static final String EMP_ISSUANCE_APPLICATION_DEEMED_WITHDRAWN = "EMP_ISSUANCE_APPLICATION_DEEMED_WITHDRAWN";
    public static final String EMP_ISSUANCE_PEER_REVIEW_REQUESTED = "EMP_ISSUANCE_PEER_REVIEW_REQUESTED";
    public static final String EMP_ISSUANCE_REGISTRY_ACCOUNT_OPENING_EVENT_SUBMITTED = "EMP_ISSUANCE_REGISTRY_ACCOUNT_OPENING_EVENT_SUBMITTED";
    public static final String EMP_ISSUANCE_APPLICATION_PEER_REVIEWER_ACCEPTED = "EMP_ISSUANCE_APPLICATION_PEER_REVIEWER_ACCEPTED";
    public static final String EMP_ISSUANCE_APPLICATION_PEER_REVIEWER_REJECTED = "EMP_ISSUANCE_APPLICATION_PEER_REVIEWER_REJECTED";
    public static final String EMP_ISSUANCE_APPLICATION_RETURNED_FOR_AMENDS = "EMP_ISSUANCE_APPLICATION_RETURNED_FOR_AMENDS";
    public static final String EMP_ISSUANCE_APPLICATION_AMENDS_SUBMITTED = "EMP_ISSUANCE_APPLICATION_AMENDS_SUBMITTED";
    public static final String EMP_ISSUANCE_RECALLED_FROM_AMENDS = "EMP_ISSUANCE_RECALLED_FROM_AMENDS";

    /**
     * EMP_NOTIFICATION
     */
    public static final String EMP_NOTIFICATION_APPLICATION_SUBMITTED = "EMP_NOTIFICATION_APPLICATION_SUBMITTED";
    public static final String EMP_NOTIFICATION_APPLICATION_CANCELLED = "EMP_NOTIFICATION_APPLICATION_CANCELLED";
    public static final String EMP_NOTIFICATION_APPLICATION_GRANTED = "EMP_NOTIFICATION_APPLICATION_GRANTED";
    public static final String EMP_NOTIFICATION_APPLICATION_REJECTED = "EMP_NOTIFICATION_APPLICATION_REJECTED";
    public static final String EMP_NOTIFICATION_APPLICATION_COMPLETED = "EMP_NOTIFICATION_APPLICATION_COMPLETED";
    public static final String EMP_NOTIFICATION_PEER_REVIEW_REQUESTED = "EMP_NOTIFICATION_PEER_REVIEW_REQUESTED";
    public static final String EMP_NOTIFICATION_APPLICATION_PEER_REVIEWER_ACCEPTED = "EMP_NOTIFICATION_APPLICATION_PEER_REVIEWER_ACCEPTED";
    public static final String EMP_NOTIFICATION_APPLICATION_PEER_REVIEWER_REJECTED = "EMP_NOTIFICATION_APPLICATION_PEER_REVIEWER_REJECTED";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_RESPONSE_SUBMITTED = "EMP_NOTIFICATION_FOLLOW_UP_RESPONSE_SUBMITTED";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_DATE_EXTENDED = "EMP_NOTIFICATION_FOLLOW_UP_DATE_EXTENDED";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMITTED = "EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMITTED";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_RETURNED_FOR_AMENDS = "EMP_NOTIFICATION_FOLLOW_UP_RETURNED_FOR_AMENDS";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_RECALLED_FROM_AMENDS = "EMP_NOTIFICATION_FOLLOW_UP_RECALLED_FROM_AMENDS";

    /**
       EMP VARIATION
    */
    public static final String EMP_VARIATION_APPLICATION_SUBMITTED = "EMP_VARIATION_APPLICATION_SUBMITTED";
    public static final String EMP_VARIATION_APPLICATION_APPROVED = "EMP_VARIATION_APPLICATION_APPROVED";
    public static final String EMP_VARIATION_APPLICATION_REJECTED = "EMP_VARIATION_APPLICATION_REJECTED";
    public static final String EMP_VARIATION_APPLICATION_DEEMED_WITHDRAWN = "EMP_VARIATION_APPLICATION_DEEMED_WITHDRAWN";
    public static final String EMP_VARIATION_PEER_REVIEW_REQUESTED = "EMP_VARIATION_PEER_REVIEW_REQUESTED";
    public static final String EMP_VARIATION_APPLICATION_REGULATOR_LED_APPROVED = "EMP_VARIATION_APPLICATION_REGULATOR_LED_APPROVED";
    public static final String EMP_VARIATION_APPLICATION_PEER_REVIEWER_ACCEPTED = "EMP_VARIATION_APPLICATION_PEER_REVIEWER_ACCEPTED";
    public static final String EMP_VARIATION_APPLICATION_PEER_REVIEWER_REJECTED = "EMP_VARIATION_APPLICATION_PEER_REVIEWER_REJECTED";
    public static final String EMP_VARIATION_APPLICATION_CANCELLED = "EMP_VARIATION_APPLICATION_CANCELLED";
    public static final String EMP_VARIATION_APPLICATION_RETURNED_FOR_AMENDS = "EMP_VARIATION_APPLICATION_RETURNED_FOR_AMENDS";
    public static final String EMP_VARIATION_APPLICATION_AMENDS_SUBMITTED = "EMP_VARIATION_APPLICATION_AMENDS_SUBMITTED";
    public static final String EMP_VARIATION_RECALLED_FROM_AMENDS = "EMP_VARIATION_RECALLED_FROM_AMENDS";

    /**
        BATCH REISSUE
     */
    public static final String EMP_BATCH_REISSUE_SUBMITTED = "EMP_BATCH_REISSUE_SUBMITTED";
    public static final String EMP_BATCH_REISSUE_COMPLETED = "EMP_BATCH_REISSUE_COMPLETED";
    public static final String EMP_REISSUE_COMPLETED = "EMP_REISSUE_COMPLETED";

    /**
     AER
     */
    public static final String AER_APPLICATION_CANCELLED_DUE_TO_EXEMPT = "AER_APPLICATION_CANCELLED_DUE_TO_EXEMPT";
    public static final String AER_APPLICATION_EXEMPTION_REVERTED = "AER_APPLICATION_EXEMPTION_REVERTED";
    public static final String AER_APPLICATION_RE_INITIATED = "AER_APPLICATION_RE_INITIATED";
    public static final String AER_APPLICATION_SENT_TO_VERIFIER = "AER_APPLICATION_SENT_TO_VERIFIER";
    public static final String AER_APPLICATION_SUBMITTED = "AER_APPLICATION_SUBMITTED";
    public static final String AER_APPLICATION_VERIFICATION_SUBMITTED = "AER_APPLICATION_VERIFICATION_SUBMITTED";
    public static final String AER_VERIFICATION_RETURNED_TO_OPERATOR = "AER_VERIFICATION_RETURNED_TO_OPERATOR";
    public static final String AER_RECALLED_FROM_VERIFICATION = "AER_RECALLED_FROM_VERIFICATION";
    public static final String AER_APPLICATION_REVIEW_SKIPPED = "AER_APPLICATION_REVIEW_SKIPPED";
    public static final String AER_APPLICATION_COMPLETED = "AER_APPLICATION_COMPLETED";
    public static final String AER_APPLICATION_RETURNED_FOR_AMENDS = "AER_APPLICATION_RETURNED_FOR_AMENDS";
    public static final String AER_APPLICATION_AMENDS_SENT_TO_VERIFIER = "AER_APPLICATION_AMENDS_SENT_TO_VERIFIER";
    public static final String AER_APPLICATION_AMENDS_SUBMITTED = "AER_APPLICATION_AMENDS_SUBMITTED";

    /**
        DOE
     */
    public static final String DOE_APPLICATION_SUBMITTED = "DOE_APPLICATION_SUBMITTED";
    public static final String DOE_APPLICATION_CANCELLED = "DOE_APPLICATION_CANCELLED";
    public static final String DOE_PEER_REVIEW_REQUESTED = "DOE_PEER_REVIEW_REQUESTED";
    public static final String DOE_PEER_REVIEWER_ACCEPTED = "DOE_PEER_REVIEWER_ACCEPTED";
    public static final String DOE_PEER_REVIEWER_REJECTED = "DOE_PEER_REVIEWER_REJECTED";
    public static final String DOE_APPLICATION_CANCELLED_DUE_TO_EXEMPT = "DOE_APPLICATION_CANCELLED_DUE_TO_EXEMPT";

    /**
     * VIR
     */
    public static final String VIR_APPLICATION_SUBMITTED = "VIR_APPLICATION_SUBMITTED";
    public static final String VIR_APPLICATION_REVIEWED = "VIR_APPLICATION_REVIEWED";
    public static final String VIR_APPLICATION_RESPONDED_TO_REGULATOR_COMMENTS = "VIR_APPLICATION_RESPONDED_TO_REGULATOR_COMMENTS";

    /**
     * REGISTRY
     */
    public static final String REGISTRY_UPDATED_EMISSIONS_EVENT_SUBMITTED = "REGISTRY_UPDATED_EMISSIONS_EVENT_SUBMITTED";
    public static final String REGISTRY_UPDATED_ACCOUNT_EVENT_SUBMITTED = "REGISTRY_UPDATED_ACCOUNT_EVENT_SUBMITTED";
    public static final String REGISTRY_REGULATOR_NOTICE_EVENT_SUBMITTED = "REGISTRY_REGULATOR_NOTICE_EVENT_SUBMITTED";

    /**
     * NON_COMPLIANCE
     */
    public static final String NON_COMPLIANCE_APPLICATION_SUBMITTED = "NON_COMPLIANCE_APPLICATION_SUBMITTED";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEW_REQUESTED = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEW_REQUESTED";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEWER_ACCEPTED = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEWER_ACCEPTED";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEWER_REJECTED = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEWER_REJECTED";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_SUBMITTED = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_SUBMITTED";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEW_REQUESTED = "NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEW_REQUESTED";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEWER_ACCEPTED = "NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEWER_ACCEPTED";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEWER_REJECTED = "NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEWER_REJECTED";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_SUBMITTED = "NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_SUBMITTED";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_SUBMITTED = "NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_SUBMITTED";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEW_REQUESTED = "NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEW_REQUESTED";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEWER_ACCEPTED = "NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEWER_ACCEPTED";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEWER_REJECTED = "NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEWER_REJECTED";
    public static final String NON_COMPLIANCE_FINAL_DETERMINATION_APPLICATION_SUBMITTED = "NON_COMPLIANCE_FINAL_DETERMINATION_APPLICATION_SUBMITTED";
    public static final String NON_COMPLIANCE_APPLICATION_CLOSED = "NON_COMPLIANCE_APPLICATION_CLOSED";
    public static final String NON_COMPLIANCE_DETAILS_AMENDED = "NON_COMPLIANCE_DETAILS_AMENDED";

    /**
     * SITE_VISIT
     */
    public static final String SITE_VISIT_APPLICATION_CANCELLED = "SITE_VISIT_APPLICATION_CANCELLED";
    public static final String SITE_VISIT_APPLICATION_SUBMITTED = "SITE_VISIT_APPLICATION_SUBMITTED";
    public static final String SITE_VISIT_PEER_REVIEW_REQUESTED = "SITE_VISIT_PEER_REVIEW_REQUESTED";
    public static final String SITE_VISIT_APPLICATION_PEER_REVIEWER_ACCEPTED = "SITE_VISIT_APPLICATION_PEER_REVIEWER_ACCEPTED";
    public static final String SITE_VISIT_APPLICATION_PEER_REVIEWER_REJECTED = "SITE_VISIT_APPLICATION_PEER_REVIEWER_REJECTED";
    public static final String SITE_VISIT_APPLICATION_RETURNED_FOR_AMENDS = "SITE_VISIT_APPLICATION_RETURNED_FOR_AMENDS";
    public static final String SITE_VISIT_RECALLED_FROM_AMENDS = "SITE_VISIT_RECALLED_FROM_AMENDS";
    public static final String SITE_VISIT_APPLICATION_AMENDS_SUBMITTED = "SITE_VISIT_APPLICATION_AMENDS_SUBMITTED";
    public static final String SITE_VISIT_APPLICATION_APPROVED = "SITE_VISIT_APPLICATION_APPROVED";
    public static final String SITE_VISIT_APPLICATION_REJECTED = "SITE_VISIT_APPLICATION_REJECTED";
}