package uk.gov.mrtm.api.workflow.request.core.domain.constants;

import lombok.experimental.UtilityClass;

@UtilityClass
public class MrtmRequestTaskActionType {
    /**
     * ACCOUNT_CLOSURE
     */
    public static final String ACCOUNT_CLOSURE_SUBMIT_APPLICATION = "ACCOUNT_CLOSURE_SUBMIT_APPLICATION";
    public static final String ACCOUNT_CLOSURE_SAVE_APPLICATION = "ACCOUNT_CLOSURE_SAVE_APPLICATION";
    public static final String ACCOUNT_CLOSURE_CANCEL_APPLICATION = "ACCOUNT_CLOSURE_CANCEL_APPLICATION";

    /**
     * EMP_ISSUANCE
     */
    public static final String EMP_ISSUANCE_SAVE_APPLICATION = "EMP_ISSUANCE_SAVE_APPLICATION";
    public static final String EMP_ISSUANCE_IMPORT_THIRD_PARTY_DATA_APPLICATION = "EMP_ISSUANCE_IMPORT_THIRD_PARTY_DATA_APPLICATION";
    public static final String EMP_ISSUANCE_IMPORT_THETIS_XML = "EMP_ISSUANCE_IMPORT_THETIS_XML";
    public static final String EMP_ISSUANCE_SUBMIT_APPLICATION = "EMP_ISSUANCE_SUBMIT_APPLICATION";
    public static final String EMP_ISSUANCE_UPLOAD_SECTION_ATTACHMENT = "EMP_ISSUANCE_UPLOAD_SECTION_ATTACHMENT";
    public static final String EMP_ISSUANCE_SAVE_APPLICATION_REVIEW = "EMP_ISSUANCE_SAVE_APPLICATION_REVIEW";
    public static final String EMP_ISSUANCE_SEND_REGISTRY_ACCOUNT_OPENING_EVENT = "EMP_ISSUANCE_SEND_REGISTRY_ACCOUNT_OPENING_EVENT";
    public static final String EMP_ISSUANCE_SAVE_REVIEW_GROUP_DECISION = "EMP_ISSUANCE_SAVE_REVIEW_GROUP_DECISION";
    public static final String EMP_ISSUANCE_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT = "EMP_ISSUANCE_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT";
    public static final String EMP_ISSUANCE_SAVE_REVIEW_DETERMINATION = "EMP_ISSUANCE_SAVE_REVIEW_DETERMINATION";
    public static final String EMP_ISSUANCE_NOTIFY_OPERATOR_FOR_DECISION = "EMP_ISSUANCE_NOTIFY_OPERATOR_FOR_DECISION";
    public static final String EMP_ISSUANCE_REVIEW_SUBMIT_PEER_REVIEW_DECISION = "EMP_ISSUANCE_REVIEW_SUBMIT_PEER_REVIEW_DECISION";
    public static final String EMP_ISSUANCE_REQUEST_PEER_REVIEW = "EMP_ISSUANCE_REQUEST_PEER_REVIEW";
    public static final String EMP_ISSUANCE_REVIEW_RETURN_FOR_AMENDS = "EMP_ISSUANCE_REVIEW_RETURN_FOR_AMENDS";
    public static final String EMP_ISSUANCE_SAVE_APPLICATION_AMEND = "EMP_ISSUANCE_SAVE_APPLICATION_AMEND";
    public static final String EMP_ISSUANCE_SUBMIT_APPLICATION_AMEND = "EMP_ISSUANCE_SUBMIT_APPLICATION_AMEND";
    public static final String EMP_ISSUANCE_RECALL_FROM_AMENDS = "EMP_ISSUANCE_RECALL_FROM_AMENDS";
    public static final String EMP_ISSUANCE_REVIEW_PREVIEW_EMP_DOCUMENT = "EMP_ISSUANCE_REVIEW_PREVIEW_EMP_DOCUMENT";
    public static final String EMP_ISSUANCE_REVIEW_PREVIEW_OFFICIAL_DOCUMENT = "EMP_ISSUANCE_REVIEW_PREVIEW_OFFICIAL_DOCUMENT";

    /**
     * EMP_NOTIFICATION
     */
    public static final String EMP_NOTIFICATION_SAVE_APPLICATION = "EMP_NOTIFICATION_SAVE_APPLICATION";
    public static final String EMP_NOTIFICATION_CANCEL_APPLICATION = "EMP_NOTIFICATION_CANCEL_APPLICATION";
    public static final String EMP_NOTIFICATION_SUBMIT_APPLICATION = "EMP_NOTIFICATION_SUBMIT_APPLICATION";
    public static final String EMP_NOTIFICATION_UPLOAD_SECTION_ATTACHMENT = "EMP_NOTIFICATION_UPLOAD_SECTION_ATTACHMENT";
    public static final String EMP_NOTIFICATION_SAVE_REVIEW_GROUP_DECISION = "EMP_NOTIFICATION_SAVE_REVIEW_GROUP_DECISION";
    public static final String EMP_NOTIFICATION_NOTIFY_OPERATOR_FOR_DECISION = "EMP_NOTIFICATION_NOTIFY_OPERATOR_FOR_DECISION";
    public static final String EMP_NOTIFICATION_REQUEST_PEER_REVIEW = "EMP_NOTIFICATION_REQUEST_PEER_REVIEW";
    public static final String EMP_NOTIFICATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION = "EMP_NOTIFICATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_SAVE_RESPONSE = "EMP_NOTIFICATION_FOLLOW_UP_SAVE_RESPONSE";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_SUBMIT_RESPONSE = "EMP_NOTIFICATION_FOLLOW_UP_SUBMIT_RESPONSE";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_EXTEND_DATE = "EMP_NOTIFICATION_FOLLOW_UP_EXTEND_DATE";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_UPLOAD_ATTACHMENT = "EMP_NOTIFICATION_FOLLOW_UP_UPLOAD_ATTACHMENT";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_SAVE_REVIEW_DECISION = "EMP_NOTIFICATION_FOLLOW_UP_SAVE_REVIEW_DECISION";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_NOTIFY_OPERATOR_FOR_DECISION = "EMP_NOTIFICATION_FOLLOW_UP_NOTIFY_OPERATOR_FOR_DECISION";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_RETURN_FOR_AMENDS = "EMP_NOTIFICATION_FOLLOW_UP_RETURN_FOR_AMENDS";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_SAVE_APPLICATION_AMEND = "EMP_NOTIFICATION_FOLLOW_UP_SAVE_APPLICATION_AMEND";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_SUBMIT_APPLICATION_AMEND = "EMP_NOTIFICATION_FOLLOW_UP_SUBMIT_APPLICATION_AMEND";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_RECALL_FROM_AMENDS = "EMP_NOTIFICATION_FOLLOW_UP_RECALL_FROM_AMENDS";

    /**
     * EMP_VARIATION
     */
    public static final String EMP_VARIATION_SAVE_APPLICATION = "EMP_VARIATION_SAVE_APPLICATION";
    public static final String EMP_VARIATION_IMPORT_THIRD_PARTY_DATA_APPLICATION = "EMP_VARIATION_IMPORT_THIRD_PARTY_DATA_APPLICATION";
    public static final String EMP_VARIATION_IMPORT_THETIS_XML = "EMP_VARIATION_IMPORT_THETIS_XML";
    public static final String EMP_VARIATION_UPLOAD_SECTION_ATTACHMENT = "EMP_VARIATION_UPLOAD_SECTION_ATTACHMENT";
    public static final String EMP_VARIATION_SUBMIT_APPLICATION = "EMP_VARIATION_SUBMIT_APPLICATION";
    public static final String EMP_VARIATION_SAVE_APPLICATION_REVIEW = "EMP_VARIATION_SAVE_APPLICATION_REVIEW";
    public static final String EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION = "EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION";
    public static final String EMP_VARIATION_SAVE_DETAILS_REVIEW_GROUP_DECISION = "EMP_VARIATION_SAVE_DETAILS_REVIEW_GROUP_DECISION";
    public static final String EMP_VARIATION_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT = "EMP_VARIATION_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT";
    public static final String EMP_VARIATION_SAVE_REVIEW_DETERMINATION = "EMP_VARIATION_SAVE_REVIEW_DETERMINATION";
    public static final String EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION = "EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION";
    public static final String EMP_VARIATION_REVIEW_PREVIEW_EMP_DOCUMENT = "EMP_VARIATION_REVIEW_PREVIEW_EMP_DOCUMENT";
    public static final String EMP_VARIATION_REVIEW_PREVIEW_OFFICIAL_DOCUMENT = "EMP_VARIATION_REVIEW_PREVIEW_OFFICIAL_DOCUMENT";
    public static final String EMP_VARIATION_SUBMIT_REGULATOR_LED_PREVIEW_EMP_DOCUMENT = "EMP_VARIATION_SUBMIT_REGULATOR_LED_PREVIEW_EMP_DOCUMENT";
    public static final String EMP_VARIATION_SUBMIT_REGULATOR_LED_PREVIEW_OFFICIAL_DOCUMENT = "EMP_VARIATION_SUBMIT_REGULATOR_LED_PREVIEW_OFFICIAL_DOCUMENT";
    public static final String EMP_VARIATION_REQUEST_PEER_REVIEW = "EMP_VARIATION_REQUEST_PEER_REVIEW";
    public static final String EMP_VARIATION_REVIEW_RETURN_FOR_AMENDS = "EMP_VARIATION_REVIEW_RETURN_FOR_AMENDS";
    public static final String EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION = "EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION";
    public static final String EMP_VARIATION_SAVE_APPLICATION_REGULATOR_LED = "EMP_VARIATION_SAVE_APPLICATION_REGULATOR_LED";
    public static final String EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION_REGULATOR_LED = "EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION_REGULATOR_LED";
    public static final String EMP_VARIATION_CANCEL_APPLICATION = "EMP_VARIATION_CANCEL_APPLICATION";
    public static final String EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_REGULATOR_LED = "EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_REGULATOR_LED";
    public static final String EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_REGULATOR_LED = "EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_REGULATOR_LED";
    public static final String EMP_VARIATION_REQUEST_PEER_REVIEW_REGULATOR_LED = "EMP_VARIATION_REQUEST_PEER_REVIEW_REGULATOR_LED";
    public static final String EMP_VARIATION_SUBMIT_APPLICATION_AMEND = "EMP_VARIATION_SUBMIT_APPLICATION_AMEND";
    public static final String EMP_VARIATION_SAVE_APPLICATION_AMEND = "EMP_VARIATION_SAVE_APPLICATION_AMEND";
    public static final String EMP_VARIATION_RECALL_FROM_AMENDS = "EMP_VARIATION_RECALL_FROM_AMENDS";

    /**
     * AER
     */
    public static final String AER_SAVE_APPLICATION = "AER_SAVE_APPLICATION";
    public static final String AER_IMPORT_THIRD_PARTY_DATA_APPLICATION = "AER_IMPORT_THIRD_PARTY_DATA_APPLICATION";
    public static final String AER_VERIFICATION_IMPORT_THIRD_PARTY_DATA_APPLICATION = "AER_VERIFICATION_IMPORT_THIRD_PARTY_DATA_APPLICATION";
    public static final String AER_UPLOAD_SECTION_ATTACHMENT = "AER_UPLOAD_SECTION_ATTACHMENT";
    public static final String AER_FETCH_EMP_LIST_OF_SHIPS = "AER_FETCH_EMP_LIST_OF_SHIPS";
    public static final String AER_SUBMIT_APPLICATION = "AER_SUBMIT_APPLICATION";
    public static final String AER_REQUEST_VERIFICATION = "AER_REQUEST_VERIFICATION";
    public static final String AER_SAVE_APPLICATION_VERIFICATION = "AER_SAVE_APPLICATION_VERIFICATION";
    public static final String AER_SUBMIT_APPLICATION_VERIFICATION = "AER_SUBMIT_APPLICATION_VERIFICATION";
    public static final String AER_VERIFICATION_RETURN_TO_OPERATOR = "AER_VERIFICATION_RETURN_TO_OPERATOR";
    public static final String AER_RECALL_FROM_VERIFICATION = "AER_RECALL_FROM_VERIFICATION";
    public static final String AER_SAVE_REVIEW_GROUP_DECISION = "AER_SAVE_REVIEW_GROUP_DECISION";
    public static final String AER_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT = "AER_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT";
    public static final String AER_COMPLETE_REVIEW = "AER_COMPLETE_REVIEW";
    public static final String AER_REVIEW_RETURN_FOR_AMENDS = "AER_REVIEW_RETURN_FOR_AMENDS";
    public static final String AER_SAVE_APPLICATION_AMEND = "AER_SAVE_APPLICATION_AMEND";
    public static final String AER_REQUEST_AMENDS_VERIFICATION = "AER_REQUEST_AMENDS_VERIFICATION";
    public static final String AER_SUBMIT_APPLICATION_AMEND = "AER_SUBMIT_APPLICATION_AMEND";
    public static final String AER_SKIP_REVIEW = "AER_SKIP_REVIEW";

    /**
     * DOE
     */
    public static final String DOE_SAVE_APPLICATION = "DOE_SAVE_APPLICATION";
    public static final String DOE_UPLOAD_ATTACHMENT = "DOE_UPLOAD_ATTACHMENT";
    public static final String DOE_SUBMIT_NOTIFY_OPERATOR = "DOE_SUBMIT_NOTIFY_OPERATOR";
    public static final String DOE_REQUEST_PEER_REVIEW = "DOE_REQUEST_PEER_REVIEW";
    public static final String DOE_SUBMIT_PEER_REVIEW_DECISION = "DOE_SUBMIT_PEER_REVIEW_DECISION";
    public static final String DOE_CANCEL_APPLICATION = "DOE_CANCEL_APPLICATION";

    /**
     * VIR
     */
    public static final String VIR_SUBMIT_APPLICATION = "VIR_SUBMIT_APPLICATION";
    public static final String VIR_UPLOAD_ATTACHMENT = "VIR_UPLOAD_ATTACHMENT";
    public static final String VIR_SAVE_APPLICATION = "VIR_SAVE_APPLICATION";
    public static final String VIR_SAVE_REVIEW = "VIR_SAVE_REVIEW";
    public static final String VIR_NOTIFY_OPERATOR_FOR_DECISION = "VIR_NOTIFY_OPERATOR_FOR_DECISION";
    public static final String VIR_SAVE_RESPOND_TO_REGULATOR_COMMENTS = "VIR_SAVE_RESPOND_TO_REGULATOR_COMMENTS";
    public static final String VIR_SUBMIT_RESPOND_TO_REGULATOR_COMMENTS = "VIR_SUBMIT_RESPOND_TO_REGULATOR_COMMENTS";

    /**
     * NON_COMPLIANCE
     */
    public static final String NON_COMPLIANCE_UPLOAD_ATTACHMENT = "NON_COMPLIANCE_UPLOAD_ATTACHMENT";
    public static final String NON_COMPLIANCE_SAVE_APPLICATION = "NON_COMPLIANCE_SAVE_APPLICATION";
    public static final String NON_COMPLIANCE_SUBMIT_APPLICATION = "NON_COMPLIANCE_SUBMIT_APPLICATION";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SAVE_APPLICATION = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SAVE_APPLICATION";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_REQUEST_PEER_REVIEW = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_REQUEST_PEER_REVIEW";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SUBMIT_PEER_REVIEW_DECISION = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SUBMIT_PEER_REVIEW_DECISION";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_NOTIFY_OPERATOR = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_NOTIFY_OPERATOR";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_SAVE_APPLICATION = "NON_COMPLIANCE_NOTICE_OF_INTENT_SAVE_APPLICATION";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_REQUEST_PEER_REVIEW = "NON_COMPLIANCE_NOTICE_OF_INTENT_REQUEST_PEER_REVIEW";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMIT_PEER_REVIEW_DECISION = "NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMIT_PEER_REVIEW_DECISION";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_NOTIFY_OPERATOR = "NON_COMPLIANCE_NOTICE_OF_INTENT_NOTIFY_OPERATOR";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_SAVE_APPLICATION = "NON_COMPLIANCE_CIVIL_PENALTY_SAVE_APPLICATION";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_NOTIFY_OPERATOR = "NON_COMPLIANCE_CIVIL_PENALTY_NOTIFY_OPERATOR";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_REQUEST_PEER_REVIEW = "NON_COMPLIANCE_CIVIL_PENALTY_REQUEST_PEER_REVIEW";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_SUBMIT_PEER_REVIEW_DECISION = "NON_COMPLIANCE_CIVIL_PENALTY_SUBMIT_PEER_REVIEW_DECISION";
    public static final String NON_COMPLIANCE_FINAL_DETERMINATION_SAVE_APPLICATION = "NON_COMPLIANCE_FINAL_DETERMINATION_SAVE_APPLICATION";
    public static final String NON_COMPLIANCE_FINAL_DETERMINATION_SUBMIT_APPLICATION = "NON_COMPLIANCE_FINAL_DETERMINATION_SUBMIT_APPLICATION";
    public static final String NON_COMPLIANCE_CLOSE_APPLICATION = "NON_COMPLIANCE_CLOSE_APPLICATION";
    public static final String NON_COMPLIANCE_AMEND_DETAILS = "NON_COMPLIANCE_AMEND_DETAILS";

    /**
     * SITE_VISIT
     */
    public static final String SITE_VISIT_SAVE_APPLICATION = "SITE_VISIT_SAVE_APPLICATION";
    public static final String SITE_VISIT_UPLOAD_ATTACHMENT = "SITE_VISIT_UPLOAD_ATTACHMENT";
    public static final String SITE_VISIT_CANCEL_APPLICATION = "SITE_VISIT_CANCEL_APPLICATION";
    public static final String SITE_VISIT_SUBMIT_APPLICATION = "SITE_VISIT_SUBMIT_APPLICATION";
    public static final String SITE_VISIT_SAVE_REVIEW_GROUP_DECISION = "SITE_VISIT_SAVE_REVIEW_GROUP_DECISION";
    public static final String SITE_VISIT_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT = "SITE_VISIT_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT";
    public static final String SITE_VISIT_REQUEST_PEER_REVIEW = "SITE_VISIT_REQUEST_PEER_REVIEW";
    public static final String SITE_VISIT_REVIEW_SUBMIT_PEER_REVIEW_DECISION = "SITE_VISIT_REVIEW_SUBMIT_PEER_REVIEW_DECISION";
    public static final String SITE_VISIT_REVIEW_RETURN_FOR_AMENDS = "SITE_VISIT_REVIEW_RETURN_FOR_AMENDS";
    public static final String SITE_VISIT_RECALL_FROM_AMENDS = "SITE_VISIT_RECALL_FROM_AMENDS";
    public static final String SITE_VISIT_SAVE_APPLICATION_AMEND = "SITE_VISIT_SAVE_APPLICATION_AMEND";
    public static final String SITE_VISIT_SUBMIT_APPLICATION_AMEND = "SITE_VISIT_SUBMIT_APPLICATION_AMEND";
    public static final String SITE_VISIT_NOTIFY_OPERATOR_FOR_DECISION = "SITE_VISIT_NOTIFY_OPERATOR_FOR_DECISION";
}
