package uk.gov.mrtm.api.workflow.request.core.domain.constants;

import lombok.experimental.UtilityClass;

@UtilityClass
public class MrtmRequestTaskActionPayloadTypes {
	/**
	 * ACCOUNT_CLOSURE
	 */
	public static final String ACCOUNT_CLOSURE_SAVE_APPLICATION_PAYLOAD = "ACCOUNT_CLOSURE_SAVE_APPLICATION_PAYLOAD";

	/**
	 * EMP_ISSUANCE
	 */
	public static final String EMP_ISSUANCE_SAVE_APPLICATION_PAYLOAD = "EMP_ISSUANCE_SAVE_APPLICATION_PAYLOAD";
	public static final String EMP_ISSUANCE_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD = "EMP_ISSUANCE_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD";
	public static final String EMP_ISSUANCE_SAVE_APPLICATION_REVIEW_PAYLOAD = "EMP_ISSUANCE_SAVE_APPLICATION_REVIEW_PAYLOAD";
	public static final String EMP_ISSUANCE_SAVE_REVIEW_GROUP_DECISION_PAYLOAD = "EMP_ISSUANCE_SAVE_REVIEW_GROUP_DECISION_PAYLOAD";
	public static final String EMP_ISSUANCE_SAVE_REVIEW_DETERMINATION_PAYLOAD = "EMP_ISSUANCE_SAVE_REVIEW_DETERMINATION_PAYLOAD";
	public static final String EMP_ISSUANCE_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD = "EMP_ISSUANCE_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD";
	public static final String EMP_ISSUANCE_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD = "EMP_ISSUANCE_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD";
	public static final String EMP_ISSUANCE_REQUEST_PEER_REVIEW_PAYLOAD = "EMP_ISSUANCE_REQUEST_PEER_REVIEW_PAYLOAD";
	public static final String EMP_ISSUANCE_SAVE_APPLICATION_AMEND_PAYLOAD = "EMP_ISSUANCE_SAVE_APPLICATION_AMEND_PAYLOAD";

	/**
	 * EMP_NOTIFICATION
	 */
	public static final String EMP_NOTIFICATION_SAVE_APPLICATION_PAYLOAD = "EMP_NOTIFICATION_SAVE_APPLICATION_PAYLOAD";
	public static final String EMP_NOTIFICATION_SAVE_REVIEW_GROUP_DECISION_PAYLOAD = "EMP_NOTIFICATION_SAVE_REVIEW_GROUP_DECISION_PAYLOAD";
	public static final String EMP_NOTIFICATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD = "EMP_NOTIFICATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD";
	public static final String EMP_NOTIFICATION_REQUEST_PEER_REVIEW_PAYLOAD = "EMP_NOTIFICATION_REQUEST_PEER_REVIEW_PAYLOAD";
	public static final String EMP_NOTIFICATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD = "EMP_NOTIFICATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD";
	public static final String EMP_NOTIFICATION_FOLLOW_UP_SAVE_RESPONSE_PAYLOAD = "EMP_NOTIFICATION_FOLLOW_UP_SAVE_RESPONSE_PAYLOAD";
	public static final String EMP_NOTIFICATION_FOLLOW_UP_EXTEND_DATE_PAYLOAD = "EMP_NOTIFICATION_FOLLOW_UP_EXTEND_DATE_PAYLOAD";
	public static final String EMP_NOTIFICATION_FOLLOW_UP_SAVE_REVIEW_DECISION_PAYLOAD = "EMP_NOTIFICATION_FOLLOW_UP_SAVE_REVIEW_DECISION_PAYLOAD";
	public static final String EMP_NOTIFICATION_FOLLOW_UP_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD = "EMP_NOTIFICATION_FOLLOW_UP_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD";
	public static final String EMP_NOTIFICATION_FOLLOW_UP_SAVE_APPLICATION_AMEND_PAYLOAD = "EMP_NOTIFICATION_FOLLOW_UP_SAVE_APPLICATION_AMEND_PAYLOAD";

	/**
	 * EMP_VARIATION
	 */
	public static final String EMP_VARIATION_SAVE_APPLICATION_PAYLOAD = "EMP_VARIATION_SAVE_APPLICATION_PAYLOAD";
	public static final String EMP_VARIATION_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD = "EMP_VARIATION_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD";
	public static final String EMP_VARIATION_SAVE_APPLICATION_REVIEW_PAYLOAD = "EMP_VARIATION_SAVE_APPLICATION_REVIEW_PAYLOAD";
	public static final String EMP_VARIATION_SAVE_DETAILS_REVIEW_GROUP_DECISION_PAYLOAD = "EMP_VARIATION_SAVE_DETAILS_REVIEW_GROUP_DECISION_PAYLOAD";
	public static final String EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION_PAYLOAD = "EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION_PAYLOAD";
	public static final String EMP_VARIATION_SAVE_REVIEW_DETERMINATION_PAYLOAD = "EMP_VARIATION_SAVE_REVIEW_DETERMINATION_PAYLOAD";
	public static final String EMP_VARIATION_REQUEST_PEER_REVIEW_PAYLOAD = "EMP_VARIATION_REQUEST_PEER_REVIEW_PAYLOAD";
	public static final String EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD = "EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD";
	public static final String EMP_VARIATION_SAVE_APPLICATION_REGULATOR_LED_PAYLOAD = "EMP_VARIATION_SAVE_APPLICATION_REGULATOR_LED_PAYLOAD";
	public static final String EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION_REGULATOR_LED_PAYLOAD = "EMP_VARIATION_SAVE_REVIEW_GROUP_DECISION_REGULATOR_LED_PAYLOAD";
	public static final String EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_REGULATOR_LED_PAYLOAD = "EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_REGULATOR_LED_PAYLOAD";
	public static final String EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_REGULATOR_LED_PAYLOAD = "EMP_VARIATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION_REGULATOR_LED_PAYLOAD";
	public static final String EMP_VARIATION_REQUEST_PEER_REVIEW_REGULATOR_LED_PAYLOAD = "EMP_VARIATION_REQUEST_PEER_REVIEW_REGULATOR_LED_PAYLOAD";
	public static final String EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD = "EMP_VARIATION_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD";
	public static final String EMP_VARIATION_SAVE_APPLICATION_AMEND_PAYLOAD = "EMP_VARIATION_SAVE_APPLICATION_AMEND_PAYLOAD";

	/**
	 * AER
	 */
	public static final String AER_SAVE_APPLICATION_PAYLOAD = "AER_SAVE_APPLICATION_PAYLOAD";
	public static final String AER_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD = "AER_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD";
	public static final String AER_VERIFICATION_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD = "AER_VERIFICATION_IMPORT_THIRD_PARTY_DATA_APPLICATION_PAYLOAD";
	public static final String AER_SAVE_APPLICATION_VERIFICATION_PAYLOAD = "AER_SAVE_APPLICATION_VERIFICATION_PAYLOAD";
	public static final String AER_VERIFICATION_RETURN_TO_OPERATOR_PAYLOAD = "AER_VERIFICATION_RETURN_TO_OPERATOR_PAYLOAD";
	public static final String AER_SAVE_REVIEW_GROUP_DECISION_PAYLOAD = "AER_SAVE_REVIEW_GROUP_DECISION_PAYLOAD";
	public static final String AER_SAVE_APPLICATION_AMEND_PAYLOAD = "AER_SAVE_APPLICATION_AMEND_PAYLOAD";
	public static final String AER_SKIP_REVIEW_PAYLOAD = "AER_SKIP_REVIEW_PAYLOAD";

	/**
	 * DOE
	 */
    public static final String DOE_SAVE_APPLICATION_PAYLOAD = "DOE_SAVE_APPLICATION_PAYLOAD";
	public static final String DOE_SUBMIT_NOTIFY_OPERATOR_PAYLOAD = "DOE_SUBMIT_NOTIFY_OPERATOR_PAYLOAD";
	public static final String DOE_REQUEST_PEER_REVIEW_PAYLOAD = "DOE_REQUEST_PEER_REVIEW_PAYLOAD";
	public static final String DOE_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD = "DOE_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD";

	/**
	 * VIR
	 */
	public static final String VIR_SAVE_APPLICATION_PAYLOAD = "VIR_SAVE_APPLICATION_PAYLOAD";
	public static final String VIR_SAVE_REVIEW_PAYLOAD = "VIR_SAVE_REVIEW_PAYLOAD";
	public static final String VIR_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD = "VIR_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD";
	public static final String VIR_SAVE_RESPOND_TO_REGULATOR_COMMENTS_PAYLOAD = "VIR_SAVE_RESPOND_TO_REGULATOR_COMMENTS_PAYLOAD";
	public static final String VIR_SUBMIT_RESPOND_TO_REGULATOR_COMMENTS_PAYLOAD = "VIR_SUBMIT_RESPOND_TO_REGULATOR_COMMENTS_PAYLOAD";

	/**
	 * NON_COMPLIANCE
	 */
	public static final String NON_COMPLIANCE_SAVE_APPLICATION_PAYLOAD = "NON_COMPLIANCE_SAVE_APPLICATION_PAYLOAD";
	public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SAVE_APPLICATION_PAYLOAD = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SAVE_APPLICATION_PAYLOAD";
	public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_REQUEST_PEER_REVIEW_PAYLOAD = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_REQUEST_PEER_REVIEW_PAYLOAD";
	public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD";
	public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_NOTIFY_OPERATOR_PAYLOAD = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_NOTIFY_OPERATOR_PAYLOAD";
	public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_SAVE_APPLICATION_PAYLOAD = "NON_COMPLIANCE_NOTICE_OF_INTENT_SAVE_APPLICATION_PAYLOAD";
	public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_REQUEST_PEER_REVIEW_PAYLOAD = "NON_COMPLIANCE_NOTICE_OF_INTENT_REQUEST_PEER_REVIEW_PAYLOAD";
	public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD = "NON_COMPLIANCE_NOTICE_OF_INTENT_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD";
	public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_NOTIFY_OPERATOR_PAYLOAD = "NON_COMPLIANCE_NOTICE_OF_INTENT_NOTIFY_OPERATOR_PAYLOAD";
	public static final String NON_COMPLIANCE_CIVIL_PENALTY_SAVE_APPLICATION_PAYLOAD = "NON_COMPLIANCE_CIVIL_PENALTY_SAVE_APPLICATION_PAYLOAD";
	public static final String NON_COMPLIANCE_CIVIL_PENALTY_NOTIFY_OPERATOR_PAYLOAD = "NON_COMPLIANCE_CIVIL_PENALTY_NOTIFY_OPERATOR_PAYLOAD";
	public static final String NON_COMPLIANCE_CIVIL_PENALTY_REQUEST_PEER_REVIEW_PAYLOAD = "NON_COMPLIANCE_CIVIL_PENALTY_REQUEST_PEER_REVIEW_PAYLOAD";
	public static final String NON_COMPLIANCE_CIVIL_PENALTY_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD = "NON_COMPLIANCE_CIVIL_PENALTY_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD";
	public static final String NON_COMPLIANCE_FINAL_DETERMINATION_SAVE_APPLICATION_PAYLOAD = "NON_COMPLIANCE_FINAL_DETERMINATION_SAVE_APPLICATION_PAYLOAD";
	public static final String NON_COMPLIANCE_CLOSE_APPLICATION_PAYLOAD = "NON_COMPLIANCE_CLOSE_APPLICATION_PAYLOAD";
	public static final String NON_COMPLIANCE_AMEND_DETAILS_PAYLOAD = "NON_COMPLIANCE_AMEND_DETAILS_PAYLOAD";

	/**
	 * SITE_VISIT
	 */
	public static final String SITE_VISIT_SAVE_APPLICATION_PAYLOAD = "SITE_VISIT_SAVE_APPLICATION_PAYLOAD";
	public static final String SITE_VISIT_SAVE_REVIEW_GROUP_DECISION_PAYLOAD = "SITE_VISIT_SAVE_REVIEW_GROUP_DECISION_PAYLOAD";
	public static final String SITE_VISIT_REQUEST_PEER_REVIEW_PAYLOAD = "SITE_VISIT_REQUEST_PEER_REVIEW_PAYLOAD";
	public static final String SITE_VISIT_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD = "SITE_VISIT_REVIEW_SUBMIT_PEER_REVIEW_DECISION_PAYLOAD";
	public static final String SITE_VISIT_SAVE_APPLICATION_AMEND_PAYLOAD = "SITE_VISIT_SAVE_APPLICATION_AMEND_PAYLOAD";
	public static final String SITE_VISIT_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD = "SITE_VISIT_NOTIFY_OPERATOR_FOR_DECISION_PAYLOAD";
}
