package uk.gov.mrtm.api.workflow.request.core.domain.constants;

import lombok.experimental.UtilityClass;

@UtilityClass
public class MrtmRequestActionPayloadType {
    /**
     * ACCOUNT_CLOSURE
     */
    public static final String ACCOUNT_CLOSURE_SUBMITTED_PAYLOAD = "ACCOUNT_CLOSURE_SUBMITTED_PAYLOAD";

    /**
     * EMP_ISSUANCE
     */
    public static final String EMP_ISSUANCE_APPLICATION_SUBMITTED_PAYLOAD = "EMP_ISSUANCE_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String EMP_ISSUANCE_APPLICATION_APPROVED_PAYLOAD = "EMP_ISSUANCE_APPLICATION_APPROVED_PAYLOAD";
    public static final String EMP_ISSUANCE_APPLICATION_DEEMED_WITHDRAWN_PAYLOAD = "EMP_ISSUANCE_APPLICATION_DEEMED_WITHDRAWN_PAYLOAD";
    public static final String EMP_ISSUANCE_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD = "EMP_ISSUANCE_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD";
    public static final String EMP_ISSUANCE_APPLICATION_RETURNED_FOR_AMENDS_PAYLOAD = "EMP_ISSUANCE_APPLICATION_RETURNED_FOR_AMENDS_PAYLOAD";
    public static final String EMP_ISSUANCE_APPLICATION_AMENDS_SUBMITTED_PAYLOAD = "EMP_ISSUANCE_APPLICATION_AMENDS_SUBMITTED_PAYLOAD";
    public static final String EMP_ISSUANCE_REGISTRY_ACCOUNT_OPENING_EVENT_SUBMITTED_PAYLOAD = "EMP_ISSUANCE_REGISTRY_ACCOUNT_OPENING_EVENT_SUBMITTED_PAYLOAD";

    /**
     * EMP_NOTIFICATION
     */
    public static final String EMP_NOTIFICATION_APPLICATION_SUBMITTED_PAYLOAD = "EMP_NOTIFICATION_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String EMP_NOTIFICATION_APPLICATION_GRANTED_PAYLOAD = "EMP_NOTIFICATION_APPLICATION_GRANTED_PAYLOAD";
    public static final String EMP_NOTIFICATION_APPLICATION_REJECTED_PAYLOAD = "EMP_NOTIFICATION_APPLICATION_REJECTED_PAYLOAD";
    public static final String EMP_NOTIFICATION_APPLICATION_COMPLETED_PAYLOAD = "EMP_NOTIFICATION_APPLICATION_COMPLETED_PAYLOAD";
    public static final String EMP_NOTIFICATION_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD = "EMP_NOTIFICATION_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_RESPONSE_SUBMITTED_PAYLOAD = "EMP_NOTIFICATION_FOLLOW_UP_RESPONSE_SUBMITTED_PAYLOAD";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_RETURNED_FOR_AMENDS_PAYLOAD = "EMP_NOTIFICATION_FOLLOW_UP_RETURNED_FOR_AMENDS_PAYLOAD";

    /**
    EMP VARIATION
    */
    public static final String EMP_VARIATION_APPLICATION_SUBMITTED_PAYLOAD = "EMP_VARIATION_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_APPROVED_PAYLOAD = "EMP_VARIATION_APPLICATION_APPROVED_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_REJECTED_PAYLOAD = "EMP_VARIATION_APPLICATION_REJECTED_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_DEEMED_WITHDRAWN_PAYLOAD = "EMP_VARIATION_APPLICATION_DEEMED_WITHDRAWN_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_REGULATOR_LED_APPROVED_PAYLOAD = "EMP_VARIATION_APPLICATION_REGULATOR_LED_APPROVED_PAYLOAD";
    public static final String EMP_VARIATION_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD = "EMP_VARIATION_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD";
    public static final String EMP_VARIATION_PEER_REVIEW_DECISION_REGULATOR_LED_SUBMITTED_PAYLOAD = "EMP_VARIATION_PEER_REVIEW_DECISION_REGULATOR_LED_SUBMITTED_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_RETURNED_FOR_AMENDS_PAYLOAD = "EMP_VARIATION_APPLICATION_RETURNED_FOR_AMENDS_PAYLOAD";
    public static final String EMP_VARIATION_APPLICATION_AMENDS_SUBMITTED_PAYLOAD = "EMP_VARIATION_APPLICATION_AMENDS_SUBMITTED_PAYLOAD";

    /**
        BATCH REISSUE
     */
    public static final String EMP_BATCH_REISSUE_SUBMITTED_PAYLOAD = "EMP_BATCH_REISSUE_SUBMITTED_PAYLOAD";
    public static final String EMP_BATCH_REISSUE_COMPLETED_PAYLOAD = "EMP_BATCH_REISSUE_COMPLETED_PAYLOAD";
    public static final String EMP_REISSUE_COMPLETED_PAYLOAD = "EMP_REISSUE_COMPLETED_PAYLOAD";

    /**
     DOE
     */
    public static final String DOE_APPLICATION_SUBMITTED_PAYLOAD = "DOE_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String DOE_APPLICATION_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD = "DOE_APPLICATION_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD";

    /**
     AER
     */
    public static final String AER_APPLICATION_SUBMITTED_PAYLOAD = "AER_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String AER_APPLICATION_VERIFICATION_SUBMITTED_PAYLOAD = "AER_APPLICATION_VERIFICATION_SUBMITTED_PAYLOAD";
    public static final String AER_VERIFICATION_RETURNED_TO_OPERATOR_PAYLOAD = "AER_VERIFICATION_RETURNED_TO_OPERATOR_PAYLOAD";
    public static final String AER_APPLICATION_COMPLETED_PAYLOAD = "AER_APPLICATION_COMPLETED_PAYLOAD";
    public static final String AER_APPLICATION_RETURNED_FOR_AMENDS_PAYLOAD = "AER_APPLICATION_RETURNED_FOR_AMENDS_PAYLOAD";
    public static final String AER_APPLICATION_AMENDS_SUBMITTED_PAYLOAD = "AER_APPLICATION_AMENDS_SUBMITTED_PAYLOAD";

    /**
     * VIR
     */
    public static final String VIR_APPLICATION_SUBMITTED_PAYLOAD = "VIR_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String VIR_APPLICATION_REVIEWED_PAYLOAD = "VIR_APPLICATION_REVIEWED_PAYLOAD";
    public static final String VIR_APPLICATION_RESPONDED_TO_REGULATOR_COMMENTS_PAYLOAD = "VIR_APPLICATION_RESPONDED_TO_REGULATOR_COMMENTS_PAYLOAD";

    /**
     * REGISTRY
     */
    public static final String REGISTRY_UPDATED_EMISSIONS_EVENT_SUBMITTED_PAYLOAD = "REGISTRY_UPDATED_EMISSIONS_EVENT_SUBMITTED_PAYLOAD";
    public static final String REGISTRY_UPDATED_ACCOUNT_EVENT_SUBMITTED_PAYLOAD = "REGISTRY_UPDATED_ACCOUNT_EVENT_SUBMITTED_PAYLOAD";
    public static final String REGISTRY_REGULATOR_NOTICE_EVENT_SUBMITTED_PAYLOAD = "REGISTRY_REGULATOR_NOTICE_EVENT_SUBMITTED_PAYLOAD";

    /**
     * NON_COMPLIANCE
     */
    public static final String NON_COMPLIANCE_APPLICATION_SUBMITTED_PAYLOAD = "NON_COMPLIANCE_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_SUBMITTED_PAYLOAD = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD = "NON_COMPLIANCE_NOTICE_OF_INTENT_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_SUBMITTED_PAYLOAD = "NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_SUBMITTED_PAYLOAD = "NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD = "NON_COMPLIANCE_CIVIL_PENALTY_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD";
    public static final String NON_COMPLIANCE_FINAL_DETERMINATION_APPLICATION_SUBMITTED_PAYLOAD = "NON_COMPLIANCE_FINAL_DETERMINATION_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String NON_COMPLIANCE_APPLICATION_CLOSED_PAYLOAD = "NON_COMPLIANCE_APPLICATION_CLOSED_PAYLOAD";
    public static final String NON_COMPLIANCE_DETAILS_AMENDED_PAYLOAD = "NON_COMPLIANCE_DETAILS_AMENDED_PAYLOAD";

    /**
     * SITE_VISIT
     */
    public static final String SITE_VISIT_APPLICATION_SUBMITTED_PAYLOAD = "SITE_VISIT_APPLICATION_SUBMITTED_PAYLOAD";
    public static final String SITE_VISIT_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD = "SITE_VISIT_PEER_REVIEW_DECISION_SUBMITTED_PAYLOAD";
    public static final String SITE_VISIT_APPLICATION_RETURNED_FOR_AMENDS_PAYLOAD = "SITE_VISIT_APPLICATION_RETURNED_FOR_AMENDS_PAYLOAD";
    public static final String SITE_VISIT_APPLICATION_AMENDS_SUBMITTED_PAYLOAD = "SITE_VISIT_APPLICATION_AMENDS_SUBMITTED_PAYLOAD";
    public static final String SITE_VISIT_APPLICATION_REVIEW_SUBMITTED_PAYLOAD = "SITE_VISIT_APPLICATION_REVIEW_SUBMITTED_PAYLOAD";
}
