package uk.gov.mrtm.api.workflow.request.core.domain.constants;

import lombok.experimental.UtilityClass;

import java.util.Set;

@UtilityClass
public class MrtmRequestTaskType {
    /**
     * ACCOUNT_CLOSURE
     */
    public static final String ACCOUNT_CLOSURE_SUBMIT = "ACCOUNT_CLOSURE_SUBMIT";

    /**
     * EMP_ISSUANCE
     */
    public static final String EMP_ISSUANCE_APPLICATION_SUBMIT = "EMP_ISSUANCE_APPLICATION_SUBMIT";
    public static final String EMP_ISSUANCE_APPLICATION_REVIEW = "EMP_ISSUANCE_APPLICATION_REVIEW";
    public static final String EMP_ISSUANCE_WAIT_FOR_REVIEW = "EMP_ISSUANCE_WAIT_FOR_REVIEW";
    public static final String EMP_ISSUANCE_APPLICATION_PEER_REVIEW = "EMP_ISSUANCE_APPLICATION_PEER_REVIEW";
    public static final String EMP_ISSUANCE_WAIT_FOR_PEER_REVIEW = "EMP_ISSUANCE_WAIT_FOR_PEER_REVIEW";
    public static final String EMP_ISSUANCE_APPLICATION_AMENDS_SUBMIT = "EMP_ISSUANCE_APPLICATION_AMENDS_SUBMIT";
    public static final String EMP_ISSUANCE_WAIT_FOR_AMENDS = "EMP_ISSUANCE_WAIT_FOR_AMENDS";
    public static final String EMP_ISSUANCE_RDE_RESPONSE_SUBMIT = "EMP_ISSUANCE_RDE_RESPONSE_SUBMIT";
    public static final String EMP_ISSUANCE_WAIT_FOR_RDE_RESPONSE = "EMP_ISSUANCE_WAIT_FOR_RDE_RESPONSE";
    public static final String EMP_ISSUANCE_RFI_RESPONSE_SUBMIT = "EMP_ISSUANCE_RFI_RESPONSE_SUBMIT";
    public static final String EMP_ISSUANCE_WAIT_FOR_RFI_RESPONSE = "EMP_ISSUANCE_WAIT_FOR_RFI_RESPONSE";
    public static final String EMP_ISSUANCE_MAKE_PAYMENT = "EMP_ISSUANCE_MAKE_PAYMENT";
    public static final String EMP_ISSUANCE_TRACK_PAYMENT = "EMP_ISSUANCE_TRACK_PAYMENT";
    public static final String EMP_ISSUANCE_CONFIRM_PAYMENT = "EMP_ISSUANCE_CONFIRM_PAYMENT";

    /**
     * EMP_NOTIFICATION
     */
    public static final String EMP_NOTIFICATION_APPLICATION_SUBMIT = "EMP_NOTIFICATION_APPLICATION_SUBMIT";
    public static final String EMP_NOTIFICATION_APPLICATION_REVIEW = "EMP_NOTIFICATION_APPLICATION_REVIEW";
    public static final String EMP_NOTIFICATION_WAIT_FOR_REVIEW = "EMP_NOTIFICATION_WAIT_FOR_REVIEW";
    public static final String EMP_NOTIFICATION_APPLICATION_PEER_REVIEW = "EMP_NOTIFICATION_APPLICATION_PEER_REVIEW";
    public static final String EMP_NOTIFICATION_WAIT_FOR_PEER_REVIEW = "EMP_NOTIFICATION_WAIT_FOR_PEER_REVIEW";
    public static final String EMP_NOTIFICATION_FOLLOW_UP = "EMP_NOTIFICATION_FOLLOW_UP";
    public static final String EMP_NOTIFICATION_WAIT_FOR_FOLLOW_UP = "EMP_NOTIFICATION_WAIT_FOR_FOLLOW_UP";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_REVIEW = "EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_REVIEW";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_REVIEW = "EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_REVIEW";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMIT = "EMP_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMIT";
    public static final String EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_AMENDS = "EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_AMENDS";

    /**
     * EMP_VARIATION
     */
    public static final String EMP_VARIATION_APPLICATION_SUBMIT = "EMP_VARIATION_APPLICATION_SUBMIT";
    public static final String EMP_VARIATION_APPLICATION_REVIEW = "EMP_VARIATION_APPLICATION_REVIEW";
    public static final String EMP_VARIATION_WAIT_FOR_REVIEW = "EMP_VARIATION_WAIT_FOR_REVIEW";
    public static final String EMP_VARIATION_APPLICATION_PEER_REVIEW = "EMP_VARIATION_APPLICATION_PEER_REVIEW";
    public static final String EMP_VARIATION_WAIT_FOR_PEER_REVIEW = "EMP_VARIATION_WAIT_FOR_PEER_REVIEW";
    public static final String EMP_VARIATION_REGULATOR_LED_APPLICATION_SUBMIT = "EMP_VARIATION_REGULATOR_LED_APPLICATION_SUBMIT";
    public static final String EMP_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEW = "EMP_VARIATION_REGULATOR_LED_APPLICATION_PEER_REVIEW";
    public static final String EMP_VARIATION_REGULATOR_LED_WAIT_FOR_PEER_REVIEW = "EMP_VARIATION_REGULATOR_LED_WAIT_FOR_PEER_REVIEW";
    public static final String EMP_VARIATION_APPLICATION_AMENDS_SUBMIT = "EMP_VARIATION_APPLICATION_AMENDS_SUBMIT";
    public static final String EMP_VARIATION_WAIT_FOR_AMENDS = "EMP_VARIATION_WAIT_FOR_AMENDS";
    public static final String EMP_VARIATION_RDE_RESPONSE_SUBMIT = "EMP_VARIATION_RDE_RESPONSE_SUBMIT";
    public static final String EMP_VARIATION_WAIT_FOR_RDE_RESPONSE = "EMP_VARIATION_WAIT_FOR_RDE_RESPONSE";
    public static final String EMP_VARIATION_RFI_RESPONSE_SUBMIT = "EMP_VARIATION_RFI_RESPONSE_SUBMIT";
    public static final String EMP_VARIATION_WAIT_FOR_RFI_RESPONSE = "EMP_VARIATION_WAIT_FOR_RFI_RESPONSE";
    public static final String EMP_VARIATION_MAKE_PAYMENT = "EMP_VARIATION_MAKE_PAYMENT";
    public static final String EMP_VARIATION_TRACK_PAYMENT = "EMP_VARIATION_TRACK_PAYMENT";
    public static final String EMP_VARIATION_CONFIRM_PAYMENT = "EMP_VARIATION_CONFIRM_PAYMENT";
    public static final String EMP_VARIATION_REGULATOR_LED_MAKE_PAYMENT = "EMP_VARIATION_REGULATOR_LED_MAKE_PAYMENT";
    public static final String EMP_VARIATION_REGULATOR_LED_TRACK_PAYMENT = "EMP_VARIATION_REGULATOR_LED_TRACK_PAYMENT";
    public static final String EMP_VARIATION_REGULATOR_LED_CONFIRM_PAYMENT = "EMP_VARIATION_REGULATOR_LED_CONFIRM_PAYMENT";

    /**
     * AER
     */
    public static final String AER_APPLICATION_SUBMIT = "AER_APPLICATION_SUBMIT";
    public static final String AER_APPLICATION_VERIFICATION_SUBMIT = "AER_APPLICATION_VERIFICATION_SUBMIT";
    public static final String AER_WAIT_FOR_VERIFICATION = "AER_WAIT_FOR_VERIFICATION";
    public static final String AER_APPLICATION_REVIEW = "AER_APPLICATION_REVIEW";
    public static final String AER_WAIT_FOR_REVIEW = "AER_WAIT_FOR_REVIEW";
    public static final String AER_APPLICATION_AMENDS_SUBMIT = "AER_APPLICATION_AMENDS_SUBMIT";
    public static final String AER_WAIT_FOR_AMENDS = "AER_WAIT_FOR_AMENDS";
    public static final String AER_AMEND_APPLICATION_VERIFICATION_SUBMIT = "AER_AMEND_APPLICATION_VERIFICATION_SUBMIT";
    public static final String AER_AMEND_WAIT_FOR_VERIFICATION = "AER_AMEND_WAIT_FOR_VERIFICATION";

    /**
     * DOE
     */
    public static final String DOE_APPLICATION_SUBMIT = "DOE_APPLICATION_SUBMIT";
    public static final String DOE_APPLICATION_PEER_REVIEW = "DOE_APPLICATION_PEER_REVIEW";
    public static final String DOE_WAIT_FOR_PEER_REVIEW = "DOE_WAIT_FOR_PEER_REVIEW";
    public static final String DOE_MAKE_PAYMENT = "DOE_MAKE_PAYMENT";
    public static final String DOE_TRACK_PAYMENT = "DOE_TRACK_PAYMENT";
    public static final String DOE_CONFIRM_PAYMENT = "DOE_CONFIRM_PAYMENT";

    /**
     * VIR
     */
    public static final String VIR_APPLICATION_SUBMIT = "VIR_APPLICATION_SUBMIT";
    public static final String VIR_APPLICATION_REVIEW = "VIR_APPLICATION_REVIEW";
    public static final String VIR_WAIT_FOR_REVIEW = "VIR_WAIT_FOR_REVIEW";
    public static final String VIR_RESPOND_TO_REGULATOR_COMMENTS = "VIR_RESPOND_TO_REGULATOR_COMMENTS";
    public static final String VIR_RFI_RESPONSE_SUBMIT = "VIR_RFI_RESPONSE_SUBMIT";
    public static final String VIR_WAIT_FOR_RFI_RESPONSE = "VIR_WAIT_FOR_RFI_RESPONSE";

    /**
     * NON_COMPLIANCE
     */
    public static final String NON_COMPLIANCE_APPLICATION_SUBMIT = "NON_COMPLIANCE_APPLICATION_SUBMIT";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_PEER_REVIEW = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_APPLICATION_PEER_REVIEW";
    public static final String NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_WAIT_FOR_PEER_REVIEW = "NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_WAIT_FOR_PEER_REVIEW";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT = "NON_COMPLIANCE_NOTICE_OF_INTENT";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_PEER_REVIEW = "NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_PEER_REVIEW";
    public static final String NON_COMPLIANCE_NOTICE_OF_INTENT_WAIT_FOR_PEER_REVIEW = "NON_COMPLIANCE_NOTICE_OF_INTENT_WAIT_FOR_PEER_REVIEW";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY = "NON_COMPLIANCE_CIVIL_PENALTY";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_PEER_REVIEW = "NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_PEER_REVIEW";
    public static final String NON_COMPLIANCE_CIVIL_PENALTY_WAIT_FOR_PEER_REVIEW = "NON_COMPLIANCE_CIVIL_PENALTY_WAIT_FOR_PEER_REVIEW";
    public static final String NON_COMPLIANCE_FINAL_DETERMINATION = "NON_COMPLIANCE_FINAL_DETERMINATION";

    /**
     * SITE_VISIT
     */
    public static final String SITE_VISIT_APPLICATION_SUBMIT = "SITE_VISIT_APPLICATION_SUBMIT";
    public static final String SITE_VISIT_APPLICATION_REVIEW = "SITE_VISIT_APPLICATION_REVIEW";
    public static final String SITE_VISIT_WAIT_FOR_REVIEW = "SITE_VISIT_WAIT_FOR_REVIEW";
    public static final String SITE_VISIT_APPLICATION_PEER_REVIEW = "SITE_VISIT_APPLICATION_PEER_REVIEW";
    public static final String SITE_VISIT_WAIT_FOR_PEER_REVIEW = "SITE_VISIT_WAIT_FOR_PEER_REVIEW";
    public static final String SITE_VISIT_APPLICATION_AMENDS_SUBMIT = "SITE_VISIT_APPLICATION_AMENDS_SUBMIT";
    public static final String SITE_VISIT_WAIT_FOR_AMENDS = "SITE_VISIT_WAIT_FOR_AMENDS";

    public Set<String> getWaitForRequestTaskTypes() {
        return Set.of(EMP_ISSUANCE_WAIT_FOR_REVIEW,
                EMP_ISSUANCE_WAIT_FOR_PEER_REVIEW,
                EMP_ISSUANCE_WAIT_FOR_AMENDS,
                EMP_ISSUANCE_WAIT_FOR_RDE_RESPONSE,
                EMP_ISSUANCE_WAIT_FOR_RFI_RESPONSE,
                EMP_NOTIFICATION_WAIT_FOR_REVIEW,
                EMP_NOTIFICATION_WAIT_FOR_PEER_REVIEW,
                EMP_NOTIFICATION_WAIT_FOR_FOLLOW_UP,
                EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_REVIEW,
                EMP_NOTIFICATION_FOLLOW_UP_WAIT_FOR_AMENDS,
                EMP_VARIATION_WAIT_FOR_REVIEW,
                EMP_VARIATION_WAIT_FOR_PEER_REVIEW,
                EMP_VARIATION_REGULATOR_LED_WAIT_FOR_PEER_REVIEW,
                EMP_VARIATION_WAIT_FOR_AMENDS,
                EMP_VARIATION_WAIT_FOR_RDE_RESPONSE,
                EMP_VARIATION_WAIT_FOR_RFI_RESPONSE,
                DOE_WAIT_FOR_PEER_REVIEW,
                AER_WAIT_FOR_VERIFICATION,
                AER_WAIT_FOR_REVIEW,
                VIR_WAIT_FOR_REVIEW,
                AER_WAIT_FOR_AMENDS,
                VIR_WAIT_FOR_RFI_RESPONSE,
                AER_AMEND_WAIT_FOR_VERIFICATION,
                NON_COMPLIANCE_INITIAL_PENALTY_NOTICE_WAIT_FOR_PEER_REVIEW,
                NON_COMPLIANCE_NOTICE_OF_INTENT_WAIT_FOR_PEER_REVIEW,
                NON_COMPLIANCE_CIVIL_PENALTY_WAIT_FOR_PEER_REVIEW,
                SITE_VISIT_WAIT_FOR_REVIEW,
                SITE_VISIT_WAIT_FOR_PEER_REVIEW,
                SITE_VISIT_WAIT_FOR_AMENDS
        );
    }

    public static Set<String> getTrackPaymentTypes() {
        return Set.of(
                DOE_TRACK_PAYMENT,
                EMP_ISSUANCE_TRACK_PAYMENT,
                EMP_VARIATION_TRACK_PAYMENT,
                EMP_VARIATION_REGULATOR_LED_TRACK_PAYMENT
        );
    }
}
